pub const DEFAULT_RIVER_NAMES: &[&str] = &[
    "aabach", "aach", "aalbach", "aalbek", "aarbach", "aare", "abakan", "abbabach", "abelitz",
    "abens", "abitser", "ablach", "abloux", "abono", "abron", "abucea", "abulog", "abzucht",
    "acha", "acher", "acheron", "acolin", "adamenka", "adda", "adelbach", "adige", "adour",
    "adzhimka", "adzva", "afimya", "afte", "ageevka", "ager", "agger", "agir", "agly", "agogna",
    "agout", "agri", "agyily", "ahbach", "ahle", "ahne", "ahrbach", "ahre", "ahse", "aich",
    "aigre", "ailette", "aille", "ailsbach", "aire", "airin", "aisch", "aise", "aisne", "aist",
    "aiterach", "aitrach", "akasjoki", "akbash", "akhtuba", "akkem", "alagnon", "aland", "alazani",
    "alazeya", "albach", "albano", "albarine", "alberche", "albula", "alchi", "aldan", "alene",
    "alento", "alesatno", "alet", "alfambra", "alhama", "allaine", "allauk", "allia", "allier",
    "allna", "allondon", "alma", "alme", "almonte", "alpe", "alrance", "alsenz", "alsma", "alster",
    "alsteran", "altaelva", "altbach", "altefeld", "altenau", "altier", "altmuhl", "altsa",
    "alturay", "alvares", "alymka", "alzette", "alzou", "amance", "amazon", "ambleve", "ambronne",
    "ameca", "amer", "amga", "amguema", "amidz", "ammer", "amper", "ampfrach", "amstel", "anabar",
    "anadyr", "anapo", "anavazh", "ance", "ancre", "andarax", "andelle", "andelot", "andelva",
    "andlau", "andura", "andyk", "anerava", "angara", "angel", "anger", "angesan", "angitola",
    "anglin", "angrapa", "anguison", "angul", "aniene", "anlauter", "ansbach", "ante", "antenne",
    "antiesen", "antrift", "anturets", "anuy", "anvoy", "anyb", "anyol", "anyu", "anzha",
    "anzirka", "aoos", "apance", "apenke", "aposa", "aragon", "arakhtey", "aramilka", "arba",
    "arbach", "arbas", "arbazh", "arbia", "arbish", "arbogne", "arborka", "arce", "archbach",
    "arconce", "arcueil", "arda", "ardeche", "ardenne", "ardon", "ardoux", "ardre", "ardusson",
    "arelga", "arentele", "areuse", "arga", "argen", "argens", "argenton", "argentor", "argun",
    "argut", "ariege", "aril", "arize", "arka", "arkavati", "arlet", "arli", "arly", "armance",
    "armancon", "arnette", "arnon", "arnoult", "arnsbach", "aroffe", "aron", "aronde", "arpe",
    "arpia", "arques", "arrats", "arre", "arros", "arroscia", "arroux", "arsha", "artibai",
    "artiere", "artuby", "artya", "arvaz", "arve", "arya", "aryntsas", "arzhava", "arzon",
    "asbeke", "aschach", "aschaff", "aschau", "aschbach", "asco", "asdorf", "aselbach", "ashkadar",
    "ashlanka", "ashlyk", "ashmat", "asphe", "asse", "asso", "asterma", "aston", "asyvvozh",
    "atlas", "atna", "atnis", "atsvezh", "attel", "attert", "aubach", "aube", "aubetin", "aubois",
    "aubonne", "audeux", "audna", "auer", "auerbach", "aufse", "augraben", "augronne", "aujon",
    "aula", "aulne", "auma", "aumance", "aume", "aune", "aunette", "aupke", "aura", "aurach",
    "aure", "auron", "auroue", "aussoue", "authie", "authion", "autize", "automne", "auve",
    "auvezere", "auxence", "auxois", "auze", "auzene", "auzon", "auzoue", "avance", "avasyega",
    "avelon", "aven", "avenbach", "aventino", "aveyron", "aviere", "avijogi", "avre", "avryuz",
    "axtbach", "ayyu", "azergues", "azvazh", "baarbach", "babitsa", "badya", "badyol", "badyu",
    "bagaryak", "bahra", "bahre", "baise", "bakalka", "baklusha", "baksan", "balanda", "balda",
    "balykley", "balyshly", "bandiat", "banfe", "baoule", "bara", "barada", "barbanne", "barbenan",
    "barguzin", "barinka", "barneva", "barnitz", "barse", "barta", "bartak", "barthe", "barupe",
    "barycz", "basento", "bashanta", "bashkaus", "basiny", "bastau", "bauna", "baunach", "bave",
    "bavona", "baybach", "baysa", "baysere", "bazlyk", "bazyana", "beaume", "bebekha", "beber",
    "beberka", "bebra", "bebrava", "becva", "beek", "beerbach", "beffer", "bega", "begeshka",
    "begna", "behobeho", "beilbach", "beise", "bekau", "beke", "bela", "belava", "belaya", "belbo",
    "belice", "belle", "belon", "belovka", "beluga", "belulik", "bembezar", "bemyzhka", "benaize",
    "benfe", "bentreff", "berd", "berdeyka", "berdiya", "bere", "berezina", "berfa", "berita",
    "berka", "berkel", "bermecke", "bermejo", "berne", "berneck", "berounka", "berste", "besbre",
    "beshkil", "betz", "beuster", "beuvron", "bevano", "bever", "bewer", "bexter", "beysug",
    "beze", "bezonde", "biaa", "biber", "bibers", "bibert", "bibiche", "bibra", "bicha", "bidasoa",
    "bidouze", "bieber", "biebrza", "bieke", "biela", "bienne", "bierawka", "bierbach", "biesme",
    "bietnitz", "bieudre", "bievre", "biferno", "bigge", "bikin", "bilawoda", "billbach", "bille",
    "bilsbek", "binitz", "binna", "binnbach", "bionne", "bira", "birkbach", "birs", "birsig",
    "biryusa", "bisenzio", "bist", "bistrice", "bityug", "biya", "bizyuk", "blaise", "blambach",
    "blanche", "blanda", "blanice", "blata", "blau", "blavet", "blees", "bleibach", "bleone",
    "blette", "blies", "blourde", "blsanka", "bobanya", "bobr", "bobruvka", "bochka", "bode",
    "bodrog", "bodva", "boeme", "boesio", "bogana", "boganida", "bohme", "boite", "boivre",
    "boize", "bokovaya", "boler", "bolland", "bolva", "bomlitz", "borbach", "borgne", "bormida",
    "borne", "boron", "bortnaya", "borulakh", "borzovka", "borzsa", "bosna", "bosoluk", "bottwar",
    "bouble", "bouchot", "boues", "boulogne", "boulou", "boulzane", "bourbre", "bourges", "bourne",
    "bouron", "boutonne", "bouvades", "bouzanne", "bowerre", "boxbach", "boye", "boyne",
    "brabecke", "bracht", "brachtpe", "bradano", "braibach", "bramau", "brame", "bramke",
    "bramont", "branna", "braubach", "braunau", "braunsel", "braye", "brda", "brebach", "breg",
    "bregava", "brembo", "bremecke", "bremke", "brend", "brenne", "brenno", "brenta", "brenz",
    "bresle", "brettach", "breuchin", "brevenne", "brevon", "brexbach", "brezna", "brezons",
    "brezou", "briance", "briese", "brigach", "brivet", "brok", "brol", "brombach", "broye",
    "brtnice", "bruche", "brucht", "bruna", "brunau", "brylyk", "brynica", "buech", "buga",
    "bugumbas", "buhler", "bulasovo", "bulatka", "buldak", "buna", "bunz", "burata", "burets",
    "bureya", "burgusta", "burkem", "burlak", "buryol", "busento", "buxach", "buzat", "buzuluk",
    "byalven", "bykovka", "bylina", "byollem", "bystra", "bystrets", "bystrice", "bystrik",
    "bytowa", "byzovka", "bzura", "cabra", "cabranka", "cabriel", "caffaro", "cance", "caramy",
    "cavone", "cehotina", "cele", "ceor", "cere", "cernon", "cerou", "cervaro", "cesano", "cesma",
    "cetina", "ceze", "chaise", "chakulka", "chalbun", "chamb", "chamka", "changara", "changpu",
    "chardym", "charysh", "chazh", "chebyu", "ched", "chedyev", "chedyu", "cheka", "chemelki",
    "chemizla", "chemnitz", "cheptsa", "cher", "chere", "chernava", "cherta", "chestka", "chevyu",
    "chibir", "chienti", "chiers", "chigir", "chigorak", "chikoy", "chingala", "chipan", "chir",
    "chirel", "chirok", "chisva", "chogray", "chortas", "chovyu", "chub", "chubyu", "chucha",
    "chudyu", "chugrim", "chuim", "chuk", "chukady", "chuksha", "chulkas", "chulym", "chupyr",
    "chur", "churbash", "churkyu", "churskoy", "chushyol", "cidacos", "ciguela", "cikola", "ciron",
    "cismon", "cixerri", "clain", "clauge", "clery", "combade", "congo", "corbones", "correze",
    "coscile", "couesnon", "cousin", "couze", "crathis", "creuse", "crumbach", "cubia", "cure",
    "cytherus", "dahle", "dahme", "dala", "dalalven", "dalke", "danilo", "danube", "darmbach",
    "darovaya", "darovka", "dase", "daugava", "dautphe", "degotlya", "delvenau", "demnitz",
    "dendalo", "dendel", "dender", "derjon", "desna", "deva", "devoll", "deyma", "dhunn",
    "dibokwe", "dichbach", "diee", "diege", "diemel", "diete", "dikabeya", "dill", "dilmezh",
    "dilsbach", "dinkel", "dinyol", "diphepe", "ditz", "divatte", "diveria", "dives", "dixence",
    "dnieper", "dniester", "dober", "dobra", "dobrach", "dobrikha", "dollbek", "domgil", "domyol",
    "donets", "dordogne", "dornbach", "dorok", "dorpe", "doryol", "doschera", "dosse", "doubs",
    "dourbie", "dourdou", "douro", "doustre", "dozmera", "dozmorka", "dragocha", "dragonja",
    "drance", "dranse", "drava", "dreisam", "drenica", "drepte", "drin", "drina", "drinjaca",
    "driska", "drome", "dronne", "dropt", "drouette", "drusel", "dubyana", "dudvah", "duhlbach",
    "dumbea", "dunajec", "dunduk", "dunnern", "dupenau", "durance", "durbeke", "durrbach",
    "durreych", "dussel", "dute", "dyorna", "dyrnas", "dzhept", "dzisna", "ebro", "ecaillon",
    "echaz", "echez", "eckbach", "ecole", "edelbach", "eder", "edoma", "edzhydva", "efanovka",
    "effelder", "efimov", "efze", "egbil", "eger", "eggel", "egobyzha", "egozikha", "egvil",
    "ehlbeck", "eider", "eine", "eipbach", "eisack", "eisbach", "eiter", "eitra", "eksey",
    "ekshal", "elbbach", "elbe", "elblag", "elde", "elga", "elista", "elkhovka", "ellbach",
    "elliaar", "elma", "elmach", "elmbach", "elnat", "elorn", "elovka", "elpe", "elsava", "else",
    "elsebach", "elsenz", "elsoff", "elte", "eltsovka", "elzbach", "emajogi", "emme", "emmelke",
    "emmer", "emsbach", "emscher", "emtsa", "emval", "endyyu", "enguri", "enipeas", "enna",
    "ennepe", "enns", "enyuvozh", "epbach", "eranka", "erbach", "erbstrom", "erdbach", "ereyol",
    "erft", "ergene", "ergil", "ergolz", "erlauf", "erle", "erms", "ernsbach", "erpe", "erse",
    "ertach", "erych", "erzen", "erzha", "eschbach", "esches", "esera", "eshka", "esla", "espe",
    "esse", "essonne", "estampon", "este", "ette", "eure", "eurotas", "evar", "evel", "evinos",
    "evre", "exter", "eyach", "eyrieux", "eysse", "ezhyesyu", "fallbach", "faulbach", "faxalven",
    "feklenka", "felda", "feldkahl", "fella", "fellach", "feltrino", "fensch", "fibreno", "fils",
    "fintau", "fischa", "fischach", "flehbach", "fliede", "floha", "flottbek", "fnjoska", "foglia",
    "folla", "fomikha", "fontanka", "forbach", "formbach", "foro", "fortore", "freebach",
    "frolikha", "frolovka", "fuhne", "fuhse", "fulda", "fullbach", "furans", "gabas", "gaia",
    "gail", "gallego", "gande", "ganges", "gansbach", "garbeeke", "gardon", "garnitsa", "garonne",
    "gasawka", "gasyu", "gauja", "gaulbach", "gavrilo", "gaybach", "gayny", "gazeille", "gebke",
    "geeste", "gehle", "geiler", "geisbach", "gelise", "genil", "genkel", "gera", "gerdau", "gers",
    "gierbach", "giesel", "gieselau", "gilgbach", "gillbach", "gilsa", "gimbach", "ginsbach",
    "giona", "giovenco", "gizheg", "gizio", "gladbach", "glan", "glane", "glanfurt", "glatt",
    "glazok", "glazyu", "glenne", "glera", "glimke", "glogn", "glomma", "glonn", "glotter",
    "gmyrdek", "gnilukha", "godapa", "gohbach", "gokhali", "goldbach", "gollach", "golo", "golsen",
    "goltzsch", "gonbinka", "gorelaya", "gorelka", "gorevka", "gorin", "goritz", "goryanka",
    "gorzente", "gose", "gosel", "gouwe", "gradac", "grenzaa", "groache", "gronau", "grube",
    "grumbach", "grumpel", "grumpen", "grunbach", "grundau", "gryonne", "guadaira", "guadajoz",
    "guadiana", "guadiaro", "guadiela", "guaiba", "gubakush", "guisane", "gundbach", "gunz",
    "gurbe", "gurinka", "gusen", "gusika", "gutach", "gutnach", "guyotte", "gyzyayol", "hadeborn",
    "haffar", "hainbach", "halach", "haller", "hamel", "hamme", "hanfbach", "harle", "hase",
    "haslach", "haune", "havel", "heder", "heesbach", "heimbach", "hellbach", "heller", "helme",
    "henne", "hensbach", "herault", "herisson", "hersmort", "hersvif", "hessel", "heubach",
    "hnilec", "hohlbach", "holtemme", "holzape", "holzbach", "holzkape", "hombach", "honne",
    "honnige", "hoppecke", "horloff", "hornad", "horsel", "houille", "hovebach", "hron", "huczwa",
    "huebra", "huillard", "huisne", "humme", "hundem", "hunte", "hurbe", "huveaune", "hvita",
    "hyllus", "ibar", "ibeyka", "ibias", "ichatka", "ichetyu", "idice", "idomorka", "idyk",
    "idzyasyu", "iftenka", "iganya", "iged", "igobla", "ihle", "ihme", "ihne", "ijssel", "ikra",
    "iksitim", "ilek", "ilesha", "ilgan", "iller", "ilme", "ilmenau", "ilova", "ilovay", "ilpe",
    "ilsbach", "ilse", "iltym", "ilya", "ilych", "imele", "imgyt", "imshegal", "imsysa", "inachos",
    "inde", "indik", "ineshka", "ingar", "ingir", "ingoda", "innbach", "innerste", "instruch",
    "inzer", "inzhura", "ioda", "ipoly", "irdym", "ireka", "irgen", "iriska", "irka", "irkut",
    "irminio", "irovka", "irtysh", "iruzha", "iryksh", "iryu", "iryuk", "irzek", "isar", "isch",
    "isel", "isen", "isenach", "isere", "iset", "ishek", "ishem", "ishet", "ishetka", "ishim",
    "ishnya", "iskar", "iskubash", "isorno", "istok", "isyelga", "itter", "ivanel", "ivitsa",
    "ivka", "ivkina", "ivrovka", "ixeure", "iyul", "izaute", "izemetka", "izer", "izeyka", "izhma",
    "izhora", "izvozh", "izyasyu", "izyayol", "izyol", "izyumka", "izyurov", "jabach", "jabalon",
    "jachen", "jade", "jadro", "jagst", "janijogi", "jarama", "jauer", "jeetzel", "jiaolai",
    "jiloca", "jishui", "jizera", "jogne", "jona", "jorsa", "jossa", "jucar", "jugowska", "julia",
    "jumme", "kabak", "kachkar", "kadam", "kadnikha", "kady", "kahl", "kainach", "kaks",
    "kalachya", "kalais", "kalas", "kalbach", "kalchan", "kalchug", "kalchyk", "kaleega", "kall",
    "kalle", "kalmius", "kalys", "kama", "kamanyol", "kamenice", "kamenka", "kammel", "kamp",
    "kamysla", "kander", "kandyz", "kapsa", "kapsha", "karagay", "karalda", "karamala", "karay",
    "karayzy", "karbach", "karkala", "karkanka", "karkaus", "karna", "karthane", "karzhay",
    "kashlyam", "kasma", "katayka", "katiss", "katka", "katlan", "katun", "katzbach", "kayberda",
    "kaydolo", "kaygarka", "kaylinka", "kayly", "kayndor", "kaysy", "kazachka", "kazanka",
    "kazhym", "kazinka", "kaziyaz", "kazokha", "kcyninka", "kedva", "kelbke", "kelnot", "kelster",
    "kelvay", "kemijoki", "kemys", "kena", "kendel", "kenzhan", "kera", "keran", "keras", "kerech",
    "kermezh", "kerspe", "kervazh", "kerzya", "keshka", "kevdom", "kevsala", "kezan", "kezva",
    "khabur", "khatanga", "khemchik", "kheta", "kholodny", "khopyor", "khutu", "khvoyka", "kicha",
    "kidash", "kiik", "kiimbay", "kikana", "kilenka", "kilik", "kilsbach", "kimrka", "kimzha",
    "kinderle", "kindyuk", "kinerka", "kinsach", "kinzig", "kirbach", "kirenga", "kirinka",
    "kirnbach", "kisherka", "kishkil", "kiskas", "kisma", "kist", "kistenli", "kitmar", "kivozh",
    "kiyayu", "kizerka", "kizesyu", "kizhmola", "kleebach", "kleppe", "klimenka", "klyuch",
    "klyusha", "knov", "knya", "kobra", "kobrynka", "kocher", "kochhart", "kochmes", "kogasha",
    "kogit", "kogyligl", "kohlbach", "kohm", "koim", "koin", "kokmanka", "kokra", "koksha",
    "kokshaga", "koktush", "kokyl", "kolbayka", "kollau", "kollbach", "kolp", "kolpyana",
    "kolubara", "kolva", "kolyma", "komariya", "komuzha", "konanyol", "koncha", "konda", "konga",
    "konsarka", "koperdan", "kopya", "korana", "kordemka", "kornezh", "korovka", "korozha",
    "korsha", "kortyu", "koryev", "kosa", "koser", "kosina", "kosinka", "kossau", "kostikha",
    "kostoyol", "kostroma", "kosva", "kosvozh", "kosyol", "kosyu", "kotuy", "kotz", "kovda",
    "kovyrza", "koybysh", "koyka", "koyma", "kozelil", "kozinka", "krabach", "krambek", "krapivka",
    "krasnaya", "kremenka", "kremnitz", "krems", "krinitsa", "krinka", "kriusha", "kriva",
    "krivaja", "krivusha", "krka", "krombach", "kronach", "kruckau", "krumbach", "krumm", "krupa",
    "krush", "krutaya", "krutikha", "krzna", "kuba", "kuban", "kubra", "kubzha", "kuchpov",
    "kuchugan", "kudelka", "kueksha", "kuhbach", "kuhlbach", "kuhrang", "kuim", "kuklyuk", "kukyu",
    "kuliga", "kulomyu", "kulsynya", "kuma", "kumlas", "kunduska", "kunesyu", "kunzhek", "kupa",
    "kupfer", "kupyrka", "kuray", "kurba", "kurbany", "kurekmas", "kurenga", "kureyka", "kurga",
    "kurinka", "kurma", "kurmanay", "kurmazy", "kurmeyka", "kurnuzh", "kurowka", "kursak",
    "kurtyuga", "kurundus", "kushalka", "kushket", "kushmana", "kushmara", "kushulga", "kusmen",
    "kustak", "kustsa", "kutema", "kutevka", "kutkus", "kutma", "kutyk", "kuyarka", "kuyary",
    "kuyelga", "kuzherka", "kuzholok", "kuzhyu", "kuzly", "kuzobyu", "kuzyol", "kuzyug", "kvina",
    "kwisa", "kyanda", "kychan", "kydzshor", "kyjovka", "kylegyu", "kyll", "kylt", "kyltymyu",
    "kyma", "kymsas", "kynshor", "kynyol", "kyodza", "kyrchma", "kyrkyzya", "kyrtau", "kyryol",
    "kyryu", "kyurzha", "kyzym", "laborec", "lachte", "lafnitz", "laguntik", "lahn", "laibach",
    "laigne", "laisbach", "lakly", "lamba", "lambach", "lambro", "lamme", "lammer", "lamna",
    "langete", "lankau", "lapkovka", "laptevka", "largue", "lasosna", "lataseno", "lato",
    "latorica", "latrop", "laubach", "lauch", "lauchert", "lauer", "laufach", "lauter", "lauwers",
    "lavant", "lavra", "laweke", "laxbach", "laya", "layma", "lazh", "lbovka", "lebed", "lebyodka",
    "leda", "lede", "lednya", "legotho", "leguer", "lehbach", "lehrde", "leibi", "leie",
    "leimbach", "lein", "leina", "leine", "leitha", "leitzach", "lekma", "lekmash", "lemance",
    "lemanka", "lembach", "lemka", "lemp", "lempe", "lempua", "lemsha", "lemyu", "lemzha",
    "lenevka", "lenka", "lenne", "lente", "lepenac", "leppe", "lepsha", "leptayol", "lepyu",
    "lergue", "lesse", "lesum", "leukbach", "levensau", "levka", "levonka", "leze", "lezha",
    "lichte", "lielupe", "lierbach", "liese", "lieser", "liffey", "likhuta", "lillach", "lima",
    "limenda", "limmat", "lindach", "linder", "linnepe", "linth", "lipacha", "lippe", "lipsha",
    "lipyanka", "liri", "lisinka", "liska", "lison", "lister", "liswarta", "litavka", "littfe",
    "lizerne", "lizonne", "llapi", "lobach", "loban", "lobbach", "lobische", "lobkha", "lochbach",
    "locheg", "locknitz", "loevka", "lohr", "lohrbach", "loing", "loir", "loire", "loisach",
    "lokchim", "loksha", "loksimer", "lombach", "lomik", "lomikha", "lominka", "lomnice", "lomya",
    "londoga", "lone", "lonza", "lopau", "loptyuga", "lopyu", "lormecke", "lorze", "losinaya",
    "losmina", "lossa", "losse", "lotsane", "lottbek", "loucka", "loucna", "loue", "lovat",
    "loymina", "lozoya", "lozva", "lubach", "lubochya", "lubsza", "luch", "luder", "ludvozh",
    "ludyana", "ludzinka", "luga", "lugovka", "luhe", "lumda", "lundyuga", "lune", "lunka",
    "lunmich", "lunponos", "lunvozh", "lunyu", "luol", "luppbode", "luthern", "lutosha", "lutter",
    "luzege", "luzhanka", "luznice", "luzoga", "lyanos", "lymva", "lyoch", "lyokkem", "lyokshor",
    "lyokyol", "lyom", "lyotma", "lystan", "lyucher", "lyumzha", "lyutenka", "lyuya", "lyuyka",
    "maalbeek", "madmas", "madon", "madzha", "magdel", "maggia", "magra", "mahanadi", "maibach",
    "main", "maine", "maisach", "maksanka", "malse", "malta", "malxe", "malyava", "malyovka",
    "mandau", "mangfall", "manguya", "mank", "manoy", "mara", "marano", "maritsa", "mark",
    "markayol", "markbach", "markha", "marmande", "marne", "maronne", "marpe", "maryan",
    "maslinka", "massa", "matachel", "maulach", "maurine", "mausbach", "maya", "mayenne",
    "maymakan", "mayzas", "mazarka", "mazik", "mazinka", "mechka", "medebach", "medem", "medoza",
    "medyanka", "megdovas", "mehdeaue", "mehe", "meie", "melach", "melbbach", "meletka", "melk",
    "mella", "mellier", "meneuz", "menkere", "menyega", "mera", "merderet", "meret", "mergbach",
    "merkova", "merwede", "merzbach", "mesvrin", "mesyu", "metauro", "metevo", "metter", "mettma",
    "metuje", "metyolka", "meuse", "meza", "mezen", "mezhovka", "miass", "micha", "michayol",
    "michayu", "midouze", "mikayol", "miljacka", "milz", "mindel", "mintsas", "miss", "mistel",
    "mitbach", "mitka", "mituva", "miyaki", "moalven", "mochan", "modan", "modau", "moesa",
    "mogza", "mohlin", "mohne", "moksha", "moll", "moloksha", "monaga", "monbach", "montone",
    "moorbach", "moosach", "moosalb", "moraca", "morava", "moravka", "mordova", "morge", "morges",
    "morkusha", "moselle", "moshlya", "mosson", "mostovka", "mouzon", "mubach", "mudora",
    "mugnone", "muhlbach", "muhlenau", "muhre", "mulde", "mulmisch", "multanka", "muluk", "mulyk",
    "mumling", "muna", "mundo", "munka", "muravka", "murbach", "murdyug", "murg", "murkozka",
    "murr", "muryu", "murz", "muse", "mushawe", "mushuga", "musirma", "muska", "mustjogi",
    "mutnitsa", "mutunya", "mutzbach", "muvizha", "muya", "mylvozh", "myrtova", "myrtyyu",
    "mysanka", "mytets", "naab", "naafbach", "nachka", "nadym", "nagold", "nahe", "nalez", "nalon",
    "nalya", "nansa", "napte", "nara", "naratly", "narchug", "narew", "narmada", "narva",
    "nashiga", "nassach", "nausta", "navia", "nebel", "nebich", "neckar", "necker", "neerdar",
    "neetze", "neez", "nega", "neger", "nekrasa", "neman", "nemdezh", "nemich", "nemyn", "nemyt",
    "nenekha", "nenga", "neretva", "nerga", "neris", "nerl", "nerskaya", "nersma", "nervion",
    "nesque", "nesse", "neste", "nestos", "nethe", "netphe", "nette", "netze", "neumagen", "neva",
    "nevezis", "nezarka", "nidda", "nidder", "nidelva", "nidz", "nied", "niedzyu", "nieme",
    "nierbach", "niers", "niese", "nieste", "nievole", "nikifora", "nile", "nilech", "nilydz",
    "nims", "ninkoma", "nisava", "nister", "nitelva", "nitra", "nivyu", "nizyana", "nobach",
    "nodoga", "noirieu", "nolgash", "nolka", "nolya", "nordbach", "norka", "norura", "nosim",
    "notec", "novik", "nozik", "nozma", "ntshe", "nugush", "nuhne", "nuksha", "nurda", "nurma",
    "nuthe", "nuzh", "nuzha", "nuzhenka", "nuzyk", "nyanda", "nyarshor", "nydyb", "nylga",
    "nylozhka", "nyobyu", "nyromka", "nysha", "nyuba", "nyukchim", "nyukzha", "nyul", "nyulach",
    "nyumled", "nyumyd", "nyurym", "nyushor", "oawa", "obdyr", "oberbek", "obva", "ocheya",
    "ochtum", "odeborn", "odenbach", "oder",
];
