/*
 * Short one-word river names for placeholder workspace branches.
 *
 * Based on the legacy Wikidata-derived list plus additional short labels and aliases
 * from Wikidata river items (`instance of` river, Q4022), normalized to lowercase
 * ASCII and filtered to single-token 4-8 character names.
 */
pub const DEFAULT_RIVER_NAMES: &[&str] = &[
    "aabach", "aach", "aalbach", "aalbek", "aarbach", "aare", "abakan", "abalakh", "abalotz",
    "abana", "abanto", "abargune", "abaro", "abay", "abbabach", "abelitz", "abendano", "abens",
    "abitara", "abitser", "abjra", "ablach", "abloux", "abola", "abono", "abrain", "abron",
    "abucea", "abulog", "abzucht", "acha", "achanan", "acher", "acheron", "acke", "acolin",
    "acupite", "adagum", "adamenka", "adda", "adelbach", "adige", "adoain", "adour", "aduros",
    "adylsu", "adzhamka", "adzhimka", "adzva", "aelva", "afimya", "afips", "afte", "agapia",
    "ageevka", "ager", "agger", "aginaga", "aginaran", "agineko", "agineta", "agir", "agluona",
    "agly", "agogna", "agout", "agri", "aguapei", "agyily", "ahbach", "aheloy", "ahle", "ahne",
    "ahrbach", "ahre", "ahrnbach", "ahse", "ahujuuha", "aiaga", "aich", "aichilik", "aiena",
    "aierdi", "aigre", "aigues", "aikoa", "ailette", "aille", "ailsbach", "aingira", "aire",
    "airin", "aisch", "aise", "aisne", "aist", "aista", "aiterach", "aitrach", "aitxu", "aitzola",
    "aizegain", "aizkurgi", "ajanda", "ajon", "akado", "akasjoki", "akbash", "akella", "akerregi",
    "akhko", "akhmanka", "akhtuba", "akinao", "akkem", "akkim", "akmena", "aknajur", "aknysta",
    "akpeozen", "aksarka", "aksay", "akshenas", "aksu", "aktashka", "aktay", "akujoki", "akular",
    "akunk", "akzharka", "alagnon", "alaguzly", "aland", "alaurte", "alay", "alazani", "alazeya",
    "alba", "albach", "albano", "albarine", "alberche", "alberich", "albitzar", "albitzu",
    "albula", "alchan", "alche", "alchi", "aldaba", "aldan", "alene", "alento", "alesatno",
    "aleshnya", "alet", "aleun", "aley", "alfambra", "algashka", "alhama", "aliaga", "alica",
    "aliiaha", "aliso", "aliyaga", "aliyaha", "alka", "allaine", "allanda", "allauk", "allia",
    "allier", "allna", "alloa", "allondon", "alma", "almala", "almaz", "almbach", "alme",
    "almonte", "alokste", "alpe", "alper", "alrance", "alsenz", "alsma", "alster", "alsteran",
    "altaelva", "altat", "altata", "altatka", "altbach", "altefeld", "altenau", "altier",
    "altmuhl", "altsa", "altun", "alturay", "altxerri", "altyn", "altzaga", "altzola", "alvares",
    "alyagysh", "alym", "alymka", "alzette", "alzou", "amanak", "amance", "amano", "amaradia",
    "amaron", "amazon", "amba", "amberd", "ambleve", "ambronne", "ambroz", "amby", "ameca", "amer",
    "ameri", "ameriko", "ametzola", "amezule", "amga", "amguema", "amidz", "amillaga", "amme",
    "ammer", "amnya", "amorda", "amper", "ampfrach", "amputa", "amstel", "amutzaga", "anabar",
    "anadyr", "anapo", "anavazh", "ance", "ancha", "ancre", "andanga", "andarax", "andelle",
    "andelot", "andelva", "andlau", "andura", "andus", "andyk", "anerava", "aneskula", "angara",
    "angel", "anger", "angesan", "angitola", "anglin", "angrapa", "anguison", "angul", "anguta",
    "anhara", "anhor", "aniene", "anila", "anish", "ankank", "anlauter", "annaz", "annoma",
    "ansari", "ansbach", "ante", "antenne", "antiesen", "antona", "antonina", "antozulo",
    "antrift", "antso", "anturets", "antxulo", "anuy", "anvoy", "anyanya", "anyb", "anyol", "anyu",
    "anzas", "anzha", "anzirka", "anzon", "anzyak", "aoos", "apaingo", "apance", "apario",
    "aparrain", "apenke", "apion", "apnerka", "aposa", "appion", "apples", "apraiz", "apse",
    "apus", "apusinas", "arach", "aragon", "arakhtey", "aramilka", "aran", "aranbero", "aranburu",
    "arando", "aransolo", "arantzar", "araotz", "aratka", "aratso", "aratz", "arba", "arbach",
    "arballo", "arbas", "arbazh", "arbezh", "arbia", "arbina", "arbish", "arbogne", "arborka",
    "arboro", "arce", "archbach", "arconce", "arcueil", "arda", "ardantza", "arde", "ardeche",
    "ardenne", "ardon", "ardost", "ardoux", "ardre", "ardusson", "arelga", "arenoso", "arentele",
    "areuse", "arfa", "arga", "argarate", "argen", "argence", "argenon", "argens", "argenton",
    "argentor", "argixao", "arguenon", "argun", "argut", "arhan", "ariege", "aril", "arintxu",
    "ariya", "arize", "arka", "arkata", "arkavati", "arlas", "arlet", "arli", "arly", "armance",
    "armancon", "armella", "armitegi", "armona", "arnaga", "arnali", "arnbach", "arnes", "arnette",
    "arnon", "arnoult", "arnsbach", "arnuki", "aroffe", "aron", "arona", "aronde", "arpe", "arpia",
    "arques", "arraiaga", "arraras", "arrarte", "arrate", "arrats", "arrazpi", "arre", "arriaga",
    "arriandi", "arrieta", "arriondo", "arritoin", "arritxia", "arrobi", "arros", "arroscia",
    "arroux", "arruena", "arsha", "artatza", "artegi", "artibai", "artiere", "artika", "artiz",
    "artshesh", "artuby", "artxube", "artya", "artzube", "artzubi", "arvaz", "arve", "arya",
    "aryanuks", "arygem", "aryntsas", "arzaneta", "arzhava", "arzinka", "arzon", "arzurre",
    "asava", "asbeke", "aschach", "aschaff", "aschau", "aschbach", "asco", "asdorf", "aselbach",
    "ashap", "ashchisu", "ashe", "ashkadar", "ashlanka", "ashlyk", "ashmat", "ashuluk", "asinaro",
    "askaga", "asopos", "asphe", "asse", "asso", "astegia", "astepe", "asterma", "asti", "aston",
    "astuieta", "asundui", "asva", "asyvvozh", "ataka", "atasa", "atemesha", "atish", "atkara",
    "atlas", "atmiss", "atna", "atnis", "atrato", "atsvezh", "attel", "attert", "attsa", "atxabal",
    "atxarte", "atxi", "atxipi", "atxispe", "atxondo", "atxu", "atxurdin", "atxuri", "aubach",
    "aubance", "aube", "aubetin", "aubois", "aubonne", "audeux", "audna", "auer", "auerbach",
    "aufse", "augraben", "augronne", "aujon", "aula", "aulne", "auma", "aumance", "aume", "aune",
    "aunette", "aupke", "aura", "aurach", "aure", "aurino", "auron", "auroue", "aussoue", "authie",
    "authion", "autise", "autize", "automne", "auve", "auvezere", "auvignon", "auxance", "auxence",
    "auxois", "auzance", "auze", "auzene", "auzon", "auzonnet", "auzoue", "avance", "avashla",
    "avasyega", "avelon", "aven", "avenbach", "aventino", "aveyron", "aviere", "avijogi", "avikne",
    "avne", "avnereka", "avre", "avryuz", "avunda", "awarua", "axpe", "axtbach", "ayat", "ayba",
    "ayega", "aygues", "ayroux", "aysaz", "aytat", "ayyaun", "ayyogan", "ayyu", "ayyuva", "azaola",
    "azergues", "azharma", "azketa", "azkoin", "azkuen", "aztiri", "azvazh", "azyash", "baarbach",
    "babitsa", "babka", "badya", "badyol", "badyu", "bagaryak", "bage", "bagoburu", "bagryazh",
    "bahlui", "bahra", "bahre", "bahu", "baise", "bakalka", "bakchar", "bake", "baklusha",
    "bakrcay", "baksan", "baky", "balai", "balan", "balanda", "balay", "balcia", "balda",
    "baljerri", "ballion", "balora", "baltym", "balykley", "balyshly", "bandais", "bandiat",
    "banfe", "bannaya", "baoule", "bara", "baraci", "barada", "barakal", "barba", "barbanne",
    "barbenan", "barda", "barguzin", "barinka", "barneva", "barnitz", "barse", "barsuk", "barta",
    "bartak", "bartemka", "barthe", "bartuva", "barupe", "barycz", "barzas", "barziya", "barzrud",
    "basabe", "basapoto", "basate", "basaula", "basento", "bashanta", "bashkaus", "basiny",
    "basoandi", "bastau", "batamay", "bater", "batha", "batiz", "baturino", "batyr", "bauna",
    "baunach", "bausa", "bave", "bavona", "baybach", "baydach", "bayeux", "baygora", "baysa",
    "baysere", "baytu", "baytugan", "baza", "bazancha", "bazas", "bazha", "bazlyk", "bazyana",
    "beaume", "bebekha", "beber", "beberka", "bebirva", "bebra", "bebrava", "bebresh", "becva",
    "bedryazh", "beek", "beerbach", "beffer", "bega", "begeshka", "begidyan", "begna", "behobeho",
    "beilbach", "beise", "beiti", "bekau", "beke", "bela", "belagua", "belaun", "belava", "belaya",
    "belbek", "belbio", "belbo", "belendiz", "beliaren", "belice", "belitsa", "belk", "belka",
    "belle", "belon", "belovka", "beluga", "belulik", "belunka", "belva", "belyanka", "bembezar",
    "beme", "bemyzhka", "benaize", "benfe", "bentreff", "beotegia", "berano", "berbaka", "berd",
    "berdeyka", "berdiya", "berduces", "bere", "bereka", "berezina", "berfa", "bergamak",
    "berheci", "berikul", "berita", "berka", "berkel", "bermecke", "bermejo", "berne", "berneck",
    "beroaga", "berounka", "berre", "berrita", "berron", "berrota", "berste", "besaire",
    "besantxa", "besbre", "beshka", "beshkil", "beson", "betelus", "betra", "betsor", "betz",
    "beune", "beuster", "beuvron", "bevano", "bever", "bevera", "bewer", "bexter", "beysug",
    "beze", "bezhka", "bezonde", "bhundoo", "biaa", "biain", "biancon", "bianea", "biasteri",
    "biber", "bibers", "bibert", "bibiche", "bibra", "bicaz", "bicha", "bidasoa", "bidekoa",
    "bidouze", "bieber", "biebrza", "bieke", "biela", "bienne", "bierawka", "bierbach", "biesme",
    "bietnitz", "bietre", "bieudre", "bieugne", "bievre", "biferno", "bigge", "bikin", "bikuray",
    "bila", "bilawoda", "bildotx", "bilka", "billbach", "bille", "bilsbek", "bine", "binglang",
    "binies", "binitz", "binna", "binnbach", "bionne", "bira", "birkbach", "birlya", "birma",
    "birs", "birsig", "birun", "birveta", "biryuch", "biryusa", "bisenzio", "biser", "bist",
    "bistrice", "bittsa", "bitxurto", "bityug", "bixente", "biya", "bizkai", "bizkanzu", "bizya",
    "bizyuk", "bjni", "blaise", "blambach", "blanche", "blanda", "blanice", "blata", "blau",
    "blavet", "blees", "bleibach", "bleone", "blette", "blies", "bloaja", "blour", "blourde",
    "blsanka", "bobanya", "bobinka", "bobr", "bobrik", "bobrovka", "bobrowka", "bobruvka", "boca",
    "bochanka", "bochikha", "bochka", "bocq", "bode", "bodrog", "bodva", "boeme", "boesio",
    "bogana", "boganida", "bohme", "boite", "boivre", "boize", "bokhta", "bokla", "bokova",
    "bokovaya", "bola", "boler", "bolintxu", "bolland", "bolva", "bomlitz", "bonatxo", "bondenau",
    "bonnee", "borbach", "bordabe", "borgne", "borimlya", "borla", "bormida", "borne", "boron",
    "bortnaya", "borulakh", "borzenka", "borzovka", "borzsa", "borzya", "bosacka", "boscq",
    "bosna", "bosoluk", "bosq", "botfei", "botna", "bottwar", "botxea", "bouble", "bouchot",
    "boues", "bouisset", "boulogne", "boulou", "boulzane", "boumelos", "bourbre", "bourges",
    "bourne", "bouron", "bourre", "boutonne", "bouvades", "bouzanne", "bowerre", "boxbach",
    "boyarka", "boye", "boyevka", "boyne", "bozorlos", "brabecke", "bracht", "brachtpe", "bradano",
    "braibach", "bramau", "brame", "bramke", "bramont", "branlin", "branna", "brassus", "braubach",
    "braunau", "braunsel", "braye", "brda", "brebach", "breche", "breg", "bregava", "brembo",
    "bremecke", "bremke", "brend", "brenne", "brennica", "brenno", "brenon", "brenta", "brenz",
    "bresle", "bresme", "bresne", "bresque", "brettach", "breuchin", "brevenne", "brevon",
    "brexbach", "brezna", "brezons", "brezou", "briance", "briese", "brigach", "brignon", "brish",
    "brive", "brivet", "brlenka", "brok", "brol", "brombach", "brovka", "broye", "brslenka",
    "brtnice", "bruant", "bruche", "brucht", "bruhne", "bruna", "brunau", "brusenka", "brusna",
    "brusun", "bruxa", "bryanka", "brylyk", "brynica", "bucarro", "buckau", "buda", "budarka",
    "budovar", "budush", "buech", "buffalo", "buga", "bugalysh", "buganak", "bugotak", "bugumbas",
    "bugunta", "bugunzh", "buguzun", "buhler", "buhlivka", "bulach", "bulasovo", "bulatka",
    "buldak", "bullupe", "bulukhta", "buna", "bunarka", "bunz", "bura", "burata", "burdas",
    "burets", "bureya", "burge", "burgusta", "burkem", "burkhan", "burlak", "burly", "burlya",
    "burminka", "burnaya", "burnot", "burnovka", "burnya", "buron", "burreiz", "bursyak",
    "burukan", "buruncha", "buryol", "busento", "busterdi", "butka", "butoniga", "buxach", "buzat",
    "buzi", "buzim", "buztin", "buzuluk", "byalven", "bychok", "bygan", "bykovka", "bylina",
    "byollem", "bystra", "bystraya", "bystrets", "bystrice", "bystrik", "bytowa", "byzovka",
    "bzura", "cabra", "cabranka", "cabriel", "caffaro", "caicus", "caillan", "calanche",
    "calorcos", "campulo", "cance", "candalas", "cando", "canne", "canner", "canonde", "cantache",
    "capus", "caramy", "cardeo", "casaluna", "casimcea", "caudau", "caudeau", "caussels", "cavone",
    "cedrino", "cehotina", "cele", "celemin", "ceor", "cephons", "cere", "cerna", "cernon",
    "cerou", "cerumen", "cervaro", "cesano", "cesma", "cetina", "ceze", "chabra", "chad", "chaga",
    "chagan", "chaise", "chakulka", "chalbun", "chalma", "chamb", "chamka", "chamlyk", "changane",
    "changara", "changeon", "changpu", "chaporro", "chardym", "charraux", "charreau", "charysh",
    "chauzh", "chavanga", "chavezi", "chayzami", "chazh", "cheba", "chebdar", "chebula", "chebyu",
    "ched", "chedyev", "chedyu", "chee", "chegon", "cheka", "chemelki", "chemizla", "chemnitz",
    "chepets", "cheptsa", "cher", "cheran", "chere", "cherga", "chermzha", "chern", "chernava",
    "chernaya", "chernyay", "chero", "cherta", "chestka", "chevyu", "chibir", "chichkan",
    "chienti", "chiers", "chigir", "chigla", "chigorak", "chikoy", "chilik", "chilipsi", "chim",
    "chinde", "chingala", "chingis", "chiola", "chipan", "chir", "chirel", "chirka", "chirok",
    "chise", "chisva", "chiuni", "chiush", "chlmec", "chogray", "chortas", "chovyu", "chqnagh",
    "chub", "chuba", "chubyu", "chucha", "chudyu", "chugor", "chugrim", "chuim", "chuk", "chukady",
    "chuksa", "chuksha", "chulas", "chulkas", "chulman", "chulym", "chuman", "chumhak", "chumoyka",
    "chumysh", "chungges", "chuplega", "chupyr", "chur", "churbash", "churkyu", "churmug",
    "churova", "churskoy", "chushyol", "chut", "chuzhga", "chuzhya", "chuzik", "chyna", "ciboule",
    "cidacos", "ciguela", "cikola", "cinieblo", "cinyps", "ciocadia", "ciron", "cirvija", "cismon",
    "cisse", "cista", "cixerri", "clain", "claise", "clauge", "clery", "clidane", "cloche",
    "clopodia", "clouere", "codera", "coise", "cojeul", "colagne", "colagnet", "cole", "cologne",
    "colostre", "coly", "combade", "congo", "conie", "corbones", "corne", "corogea", "correze",
    "coscile", "cotmeana", "coudols", "coudre", "couesnon", "coulazou", "cousance", "cousin",
    "couze", "covurlui", "crathis", "credogne", "crempse", "creuen", "creuse", "crevoux", "cricov",
    "crieulon", "crueize", "crumbach", "crusnes", "cubelle", "cubia", "cubry", "cugir", "curcuey",
    "cure", "curretia", "cututa", "cypa", "cytherus", "dabryca", "dadou", "dahle", "dahme",
    "dajna", "daka", "dakh", "dala", "dalalven", "dalke", "dande", "danilo", "danube", "danyol",
    "daoulas", "daravka", "darba", "dargo", "darmbach", "darovaya", "darovka", "dase", "daugava",
    "dautphe", "decours", "dedovka", "degotlya", "delvenau", "deme", "demid", "demkina", "demnitz",
    "demyanka", "dendalo", "dendel", "dender", "derbeke", "derbul", "derehlui", "derelui",
    "derjon", "derkul", "derna", "derwent", "derzha", "deskarga", "desna", "deva", "devitsa",
    "devoll", "deyma", "deza", "dheune", "dhunn", "dhuy", "dibokwe", "dichbach", "dichnya", "diee",
    "diege", "diemel", "dien", "diete", "dikabeya", "dill", "dilmezh", "dilsbach", "dinamo",
    "dinan", "dinkel", "dinoorab", "dintel", "dinurab", "dinyol", "diosaz", "diphepe", "ditz",
    "divatte", "dive", "diveria", "dives", "dixence", "dnieper", "dniester", "dober", "dobka",
    "dobra", "dobrach", "dobrikha", "dobritsa", "dobsha", "doch", "does", "doire", "dokka",
    "dolaison", "dolaizon", "dolgaya", "dollbek", "doller", "dollnitz", "doloi", "dolon", "dolra",
    "domashka", "domgil", "domingo", "domyol", "donets", "donovka", "dordogne", "dorka",
    "dornbach", "dorok", "dorpe", "doryol", "doschera", "dosse", "doubs", "doulon", "doulou",
    "dourbie", "dourdene", "dourdou", "dourdu", "dourduff", "douro", "doustre", "dovern",
    "dozmera", "dozmorka", "dozovka", "dragocha", "dragonja", "drance", "dranse", "drava",
    "dreisam", "drenica", "drepte", "drezna", "drin", "drina", "drinjaca", "driska", "drome",
    "dronne", "dropt", "drouette", "druja", "drusel", "drutupis", "dubna", "dubyana", "dudvah",
    "duhlbach", "dumbea", "dumka", "dunaeva", "dunajec", "dunayeva", "dunduk", "dunnern",
    "dupenau", "durance", "durbeke", "durbion", "durgeon", "durla", "durrbach", "durreych",
    "dussel", "dute", "dvinitsa", "dyorna", "dyorzha", "dyrnas", "dysh", "dysna", "dzelda",
    "dzhallar", "dzharly", "dzhept", "dzhivus", "dzhurich", "dzhutsa", "dzidzi", "dzisna",
    "ebrach", "ebro", "ebron", "ecaillon", "echaz", "echez", "eckbach", "ecole", "edelbach",
    "edenga", "eder", "edigan", "edoma", "edzhydva", "efanovka", "effelder", "efimov", "efze",
    "egbil", "eger", "eggel", "egiaundi", "egierre", "egiguren", "egilaun", "egillor", "egobyzha",
    "egolyakh", "egozikha", "egray", "egrinka", "eguren", "egurrola", "egurtzao", "egvil",
    "ehebach", "ehlbeck", "eider", "eidselva", "einch", "eine", "eipbach", "eisack", "eisbach",
    "eiter", "eitra", "eitzaga", "ejin", "ekityki", "eksey", "ekshal", "ekstal", "ekylchak",
    "elangash", "elbak", "elbbach", "elbe", "elblag", "elbsche", "elcoaz", "elda", "elde",
    "elegest", "elet", "elez", "elga", "elisara", "elisera", "elisson", "elista", "elkhovka",
    "ellbach", "elle", "eller", "elliaar", "elma", "elmach", "elmane", "elmbach", "elnat",
    "elomza", "elorn", "elorz", "elosegi", "elosu", "elovitsa", "elovka", "elpe", "elpin", "elsa",
    "elsava", "else", "elsebach", "elsenz", "elsha", "elshanka", "elsoff", "elta", "elte",
    "eltsovka", "elutzar", "elva", "elyuga", "elzbach", "emajogi", "embolat", "emekh", "emme",
    "emmelke", "emmer", "emsbach", "emscher", "emse", "emtsa", "emval", "endrika", "endyuga",
    "endyyu", "engish", "enguri", "enipeas", "enna", "ennepe", "enns", "entala", "enyu",
    "enyuvozh", "epbach", "epele", "erain", "eranka", "erbach", "erbek", "erbstrom", "erco",
    "erdbach", "erdva", "erentzin", "eretza", "ereyol", "erft", "ergene", "ergil", "ergolz",
    "erla", "erlau", "erlauf", "erle", "erms", "ernati", "ernsbach", "erope", "erpe", "erpf",
    "erramu", "erramudi", "errazti", "erretola", "errezil", "errola", "errondo", "errotea", "erse",
    "ertach", "ertzile", "erve", "erych", "erzen", "erzha", "eschach", "eschbach", "esches",
    "escotais", "escourou", "eselbach", "esera", "eshka", "esica", "esla", "esna", "espaltza",
    "esparbe", "espe", "esse", "essonne", "estampon", "este", "estozi", "estrigon", "esves",
    "esvre", "etarte", "ette", "etxabar", "etxeru", "etze", "euerbach", "eulach", "eurajoki",
    "eure", "eurotas", "euzta", "evar", "evbaza", "evel", "evinos", "evre", "exter", "eyach",
    "eynch", "eyre", "eyrieux", "eysse", "ezcaniz", "ezhreka", "ezhuga", "ezhyesyu", "eziaga",
    "ezkaltzu", "ezki", "ezkurmin", "eztanda", "fallbach", "fare", "farma", "fars", "faulbach",
    "faxalven", "feklenka", "felda", "feldaist", "feldkahl", "fella", "fellach", "feltrino",
    "feme", "fensch", "fessard", "fibreno", "filinka", "fils", "fintau", "firiza", "firsovka",
    "fisag", "fischa", "fischach", "fiumorbo", "fiychay", "fizes", "flappach", "flaz", "fleche",
    "flehbach", "fleuth", "fliede", "flis", "flisa", "flobach", "floha", "flottbek", "flume",
    "flumen", "fnjoska", "foglia", "folla", "fomikha", "fond", "fontanka", "forbach", "formbach",
    "foro", "fortore", "fosse", "francolu", "franki", "frankio", "fredda", "freebach", "frieda",
    "frolikha", "frolovka", "fryba", "fuhne", "fuhse", "fulda", "fullbach", "furan", "furans",
    "fure", "furieuse", "fusain", "gabas", "gadalin", "gaia", "gail", "gailbach", "gairezi",
    "galardi", "galeizon", "galina", "galka", "gallego", "galsuna", "galtzaur", "galya",
    "ganaveix", "gande", "ganges", "gansbach", "garbeeke", "gardon", "gareyka", "garnitsa",
    "garonne", "garun", "gasawka", "gasyu", "gauja", "gaulbach", "gavrilo", "gaybach", "gayny",
    "gazatza", "gazeille", "geahkkil", "geavvu", "gebke", "geer", "geeste", "geghard", "gehle",
    "geiler", "gein", "geisbach", "gelbach", "gelbke", "geldieta", "gelise", "genesh", "genil",
    "genkel", "gennach", "gera", "gerdau", "germaine", "gers", "gezain", "gierbach", "giesel",
    "gieselau", "gieseler", "giffre", "gigi", "gilancay", "gilgbach", "gillbach", "gilsa",
    "gimbach", "gimone", "ginsbach", "giona", "giovenco", "girvas", "giscle", "gizheg", "gizhga",
    "gizhiga", "gizia", "gizio", "gladbach", "gladzor", "glan", "gland", "glane", "glanfurt",
    "glatt", "glazok", "glazyu", "glenne", "glenner", "glera", "glimke", "glogn", "glomma",
    "glonn", "glotter", "gluboky", "gmyrdek", "gndadzor", "gnilukha", "gnilusha", "gnishik",
    "godapa", "godovo", "gohbach", "goikoa", "gokhali", "golaya", "goldach", "goldbach", "golinga",
    "gollach", "golo", "golsen", "goltva", "goltzsch", "golubaya", "gomraget", "gona", "gonbinka",
    "gorelaya", "gorelka", "gorevka", "gorin", "goritz", "gornaya", "gorodnya", "gorosti",
    "gorritxo", "goryanka", "gorzente", "gose", "gosel", "gostila", "gouwe", "govza", "gozategi",
    "grachi", "gradac", "graon", "grazal", "grenette", "grenzaa", "gresse", "griva", "groache",
    "gronau", "grosne", "grouche", "grube", "grumbach", "grumpel", "grumpen", "grunbach",
    "grundau", "gryazna", "gryonne", "guadaira", "guadajoz", "guadiana", "guadiaro", "guadiela",
    "guagno", "guaiba", "guaire", "guama", "gubakush", "gubenka", "gubs", "guerbe", "guil",
    "guindy", "guisane", "gulp", "gumbeyka", "gundbach", "gundelen", "gunz", "gurbe", "gurinka",
    "gurkam", "guruchay", "gusar", "guscica", "guscina", "gusen", "gusika", "gusikha", "gusinka",
    "gutach", "gutnach", "guyonne", "guyotte", "gvozna", "gyda", "gyrba", "gyzyayol", "hadeborn",
    "haffar", "hagider", "hainbach", "hakhum", "halach", "halbica", "halbitsa", "haller",
    "halmagel", "halsbach", "hamel", "hamme", "hanfbach", "hante", "hantes", "hapa", "harkan",
    "harle", "hase", "haslach", "haune", "hautai", "havel", "havi", "havre", "heder", "heesbach",
    "heihe", "heimbach", "heishui", "helbeek", "helisson", "hellbach", "helle", "heller",
    "helmbach", "helme", "hemepane", "henaa", "henar", "henne", "hensbach", "hepa", "herault",
    "herisson", "herk", "hersmort", "hersvif", "hertsa", "hessel", "heubach", "hewa", "hill",
    "hnilec", "hoegne", "hoene", "hohlbach", "holmau", "holtemme", "holzape", "holzbach",
    "holzkape", "hombach", "honne", "honnige", "hoppecke", "horloff", "hornad", "horsel",
    "hosbach", "hospital", "houille", "hovebach", "hovtva", "hron", "huab", "huczwa", "huebra",
    "huillard", "huisne", "humme", "hundem", "hunte", "hunze", "hurbe", "huveaune", "hvita",
    "hvozna", "hwozna", "hwoznia", "hyllus", "ibar", "ibarrola", "ibeni", "iberre", "ibeyka",
    "ibias", "ibreda", "icha", "ichatka", "ichetyu", "ichkina", "ichma", "idice", "idomorka",
    "idyk", "idzyasyu", "iftenka", "iganya", "igaran", "iged", "igeldegi", "igerola", "iginka",
    "ignon", "igobla", "igol", "igrovka", "igurutz", "ihle", "ihme", "ihne", "iijoki", "ijalde",
    "ijssel", "ikaiburu", "ikat", "ikelemba", "ikhala", "ikra", "iksa", "iksitim", "ilek",
    "ilesha", "ileza", "ilgan", "ilim", "iller", "illon", "ilma", "ilme", "ilmenau", "ilmovka",
    "ilova", "ilovatka", "ilovay", "ilpe", "ilsbach", "ilse", "iltym", "ilunpe", "ilya", "ilyaska",
    "ilych", "imaya", "imayka", "imele", "imergue", "imgyt", "imshegal", "imsysa", "imula", "imza",
    "inachos", "incon", "inde", "indik", "ineshka", "ineya", "ingar", "ingir", "ingoda", "ingon",
    "innbach", "innerste", "inoch", "inokovka", "inopash", "insarka", "instruch", "inturia",
    "intzegiz", "inva", "inya", "inyukha", "inza", "inzaga", "inzer", "inzhura", "inzia", "ioda",
    "ioutynya", "ipoly", "iraban", "iramain", "irance", "irazu", "irdom", "irdym", "ireka",
    "irfon", "irgen", "iriska", "irka", "irkley", "irklii", "irkliy", "irkut", "irminio", "irmiza",
    "irovka", "irsa", "irtek", "irtuona", "irtysh", "iruzha", "irvanets", "iryksh", "iryu",
    "iryuk", "irzek", "irzha", "isac", "isar", "isas", "isch", "isel", "isen", "isenach", "isere",
    "iset", "ishek", "ishem", "ishet", "ishetka", "ishim", "ishnya", "ishyugan", "isildu", "iska",
    "iskar", "iskavozh", "iskir", "isklida", "iskra", "iskubash", "islac", "islach", "isop",
    "isorno", "issyk", "ista", "istok", "isuela", "isui", "isusa", "isyelga", "itinka", "itomlya",
    "itter", "ituino", "iturbe", "iturbil", "iturgune", "iturrao", "iturrina", "iturripe",
    "itxosta", "ityakh", "iupshara", "ivanel", "ivanovka", "ivanyrs", "ivas", "ivdel", "ivenka",
    "ivitsa", "ivka", "ivkina", "ivotka", "ivrovka", "ixeure", "iyebora", "iyul", "iyyoki",
    "izartza", "izaute", "izbalyk", "izdetel", "izemetka", "izer", "izeyka", "izgozhka", "izhma",
    "izhora", "izlap", "iznair", "iztinga", "iztok", "izuski", "izver", "izvozh", "izyasyu",
    "izyayol", "izyly", "izyol", "izyumka", "izyurov", "jabach", "jabalon", "jabron", "jachen",
    "jadarre", "jade", "jadro", "jagst", "jaio", "jamagne", "janijogi", "jarama", "jarbutak",
    "jaudy", "jauer", "jaunay", "jauregi", "jeetzel", "jeker", "jelesna", "jelovice", "jerice",
    "jesica", "jiaolai", "jiesia", "jiet", "jiloca", "jishui", "jizera", "jizerka", "jogne",
    "jolan", "jona", "jorsa", "jossa", "jourdane", "joyeuse", "joyuelo", "juanzar", "jucar",
    "juenes", "jugowska", "julia", "jumme", "juoda", "jure", "kabak", "kacharma", "kachkar",
    "kachmash", "kachovka", "kadam", "kadnikha", "kadrin", "kady", "kaghzvan", "kahan", "kahl",
    "kaikos", "kailda", "kainach", "kaklash", "kakmozh", "kaks", "kakva", "kalachya", "kalais",
    "kalajoki", "kalakan", "kalamua", "kalas", "kalaus", "kalbach", "kalchan", "kalchug",
    "kalchyk", "kaleega", "kaley", "kalguty", "kalindi", "kalisara", "kalitva", "kall", "kalle",
    "kalma", "kalmayur", "kalmius", "kalnupe", "kalpak", "kaltan", "kaltarak", "kaltis", "kalys",
    "kalyug", "kama", "kamanyol", "kambarka", "kamenice", "kamenka", "kammel", "kamp", "kamysla",
    "kamzolka", "kana", "kanaksha", "kanan", "kanda", "kander", "kandyz", "kankanda", "kanpazar",
    "kanuk", "kanyrka", "kapanaga", "kapiru", "kapos", "kapsa", "kapsha", "karachan", "karagay",
    "karagem", "karakan", "karakaya", "karakhan", "karakol", "karalda", "karama", "karamala",
    "karamaly", "karas", "karasu", "karasul", "karatyuk", "karay", "karayets", "karayzy",
    "karbach", "kardail", "karga", "kargalka", "karisan", "karitsa", "karkala", "karkamo",
    "karkanka", "karkaus", "karmala", "karmalka", "karmanga", "karna", "karnay", "karobi",
    "karpina", "karpiya", "karsunka", "karthane", "karzhay", "kasatka", "kashirka", "kashlam",
    "kashlyam", "kashma", "kashuni", "kasma", "kasmarka", "kasnya", "kassa", "kast", "kaster",
    "kastillo", "kata", "katantsa", "katara", "kataran", "katarysh", "katategi", "katayga",
    "katayka", "katiss", "katka", "katlan", "katroma", "katun", "katxiti", "katyk", "katylga",
    "katysh", "katzbach", "kaulina", "kavozha", "kavya", "kavycha", "kaya", "kayberda", "kaydolo",
    "kaygarka", "kaylinka", "kayly", "kayndor", "kayrakly", "kaysy", "kazachka", "kazanka",
    "kazaune", "kazha", "kazhym", "kazinka", "kaziyaz", "kazokha", "kazyr", "kcyninka", "kedva",
    "kelbke", "kele", "kelnot", "kelster", "keltom", "kelvat", "kelvay", "kema", "kemal",
    "kembach", "kemijoki", "kemys", "kena", "kenas", "kendel", "kengkeme", "kennet", "kenzhan",
    "kenzhe", "kera", "keran", "keras", "kercha", "kerech", "kerest", "kermezh", "kers", "kerspe",
    "kervazh", "kerzya", "keshka", "kestanty", "kestymka", "kevda", "kevdom", "kevojoki",
    "kevrolka", "kevsala", "keza", "kezan", "kezivka", "kezva", "khabur", "khamra", "khanmey",
    "kharinka", "khartes", "kharyaga", "khatanga", "khatyrka", "khemchik", "kheta", "khetta",
    "kheu", "khirla", "khirlep", "khobeyu", "kholodny", "kholok", "khomora", "khopyor", "khorgas",
    "khorgos", "khorobra", "khorsa", "khot", "khotcha", "khoyakha", "khuba", "khudolaz", "khupta",
    "khutorka", "khutu", "khvoyka", "kiavu", "kiblych", "kicha", "kidash", "kidero", "kidysh",
    "kidyuga", "kiembay", "kiik", "kiimbay", "kika", "kikana", "kilega", "kilenka", "kilik",
    "kilsbach", "kimreka", "kimrka", "kimzha", "kinarra", "kinderle", "kindyuk", "kinema",
    "kinenin", "kinerka", "kinoi", "kinsach", "kinterep", "kinzig", "kirbach", "kirenga", "kirga",
    "kirganik", "kirinka", "kirnbach", "kirsna", "kirva", "kisema", "kisha", "kisherka", "kishkil",
    "kiskas", "kisma", "kist", "kistenli", "kitap", "kitmar", "kiuy", "kivach", "kivijoki",
    "kivozh", "kiyauk", "kiyayu", "kiyazy", "kiyuk", "kizak", "kizas", "kizel", "kizelka",
    "kizerka", "kizesyu", "kizhmola", "kizilka", "kizugawa", "kleebach", "klenice", "kleppe",
    "klimenka", "klinke", "klyuch", "klyuchi", "klyusha", "knov", "knya", "kobla", "kobra",
    "kobrynka", "kochenga", "kocher", "kochhart", "kochmes", "koda", "kodacha", "kodz", "koelga",
    "kogasha", "koghb", "kogit", "kogozes", "kogyligl", "kohlbach", "kohm", "koim", "koin",
    "kokmanka", "kokosch", "kokpekti", "kokpela", "kokra", "koksha", "kokshaga", "koktush",
    "kokuy", "kokuzek", "kokyl", "kola", "kolba", "kolbayka", "koldoma", "kolenga", "kolezhma",
    "kollau", "kollbach", "kolodnya", "kolonga", "kolos", "kolp", "kolpenka", "kolpyana",
    "koltyrak", "kolubara", "kolva", "kolych", "kolyma", "komariya", "kombars", "komela", "komsha",
    "komuzha", "komyola", "konanyol", "koncha", "konda", "kondas", "kondoba", "kondoka", "konga",
    "kongora", "konnitsa", "kononovo", "konovazh", "konsarka", "konto", "kontokki", "koperdan",
    "kopya", "kopyl", "korana", "korba", "korbylka", "kordemka", "kordyaga", "kordyu", "korga",
    "korgova", "kori", "korma", "kornezh", "korovka", "korozha", "korsch", "korsha", "korshazh",
    "kortatxo", "kortatxu", "kortazar", "kortea", "kortyu", "kortyuga", "koryev", "kosa", "koser",
    "koses", "kosets", "kosh", "kosina", "kosinka", "kossau", "kostikha", "kostoyol", "kostrina",
    "kostroma", "kostrzyn", "kosva", "kosvozh", "kosyl", "kosyol", "kosyu", "kotbach", "kotel",
    "kotuy", "kotyol", "kotys", "kotz", "koungous", "kovach", "kovaksa", "kovashi", "kovda",
    "kovozha", "kovriga", "kovyrza", "kovzha", "koybysh", "koyen", "koyka", "koyma", "koynikha",
    "koyon", "kozelil", "kozha", "kozhoyka", "kozhva", "kozinka", "kozla", "kozul", "krabach",
    "krambek", "krapivka", "krasna", "krasnaya", "kremenka", "kremnitz", "krems", "krinitsa",
    "krinka", "kriusha", "kriva", "krivaja", "krivan", "krivaya", "krivusha", "krka", "kroma",
    "krombach", "kronach", "krounka", "kruckau", "krumbach", "krumm", "kruoja", "krupa", "krupeja",
    "krupeya", "krupina", "krush", "krushma", "krutaya", "krutikha", "krutynia", "kryazhim",
    "krzna", "kshen", "kshtut", "kuba", "kuban", "kubanka", "kubr", "kubra", "kubzha", "kucha",
    "kuchinka", "kuchpov", "kuchugan", "kuchuk", "kudelka", "kudesna", "kudka", "kudrikha",
    "kueksha", "kuguner", "kugutyk", "kuhbach", "kuhlbach", "kuhrang", "kuim", "kukazar",
    "kukhtur", "kukhtym", "kukhva", "kuklyuk", "kukolka", "kukrauk", "kukshum", "kukyu", "kula",
    "kulatka", "kuliga", "kulomyu", "kuloy", "kulsynya", "kulunda", "kulyogan", "kulyok", "kuma",
    "kumbasa", "kumlaan", "kumlas", "kumlyak", "kumma", "kumsa", "kumylga", "kumzas", "kuna",
    "kunashka", "kunda", "kundala", "kunduska", "kunes", "kunesyu", "kunges", "kungess", "kunggus",
    "kunki", "kunost", "kunyanka", "kunzhek", "kunzhik", "kuosine", "kupa", "kupfer", "kupuri",
    "kupyrka", "kurakh", "kuray", "kurba", "kurbany", "kurbysh", "kurdomka", "kurdyum", "kurejoki",
    "kurekmas", "kurelga", "kurenga", "kureyka", "kurga", "kurganka", "kurgash", "kurilka",
    "kurinka", "kurkatau", "kurlak", "kurley", "kurma", "kurmanay", "kurmazy", "kurmeyka",
    "kurmysh", "kurnuzh", "kuroma", "kuromsha", "kurowka", "kurpita", "kurpota", "kursak",
    "kurtyuga", "kurtzio", "kurundus", "kurushan", "kurutze", "kuryaksa", "kushalka", "kushket",
    "kushmana", "kushmara", "kushulga", "kushva", "kuskullu", "kusmen", "kustak", "kustsa",
    "kutamysh", "kutato", "kutema", "kutevka", "kutkus", "kutma", "kutok", "kutujoki", "kutuluk",
    "kutyk", "kuyacha", "kuyagan", "kuyarka", "kuyary", "kuyeda", "kuyelga", "kuyevata", "kuzha",
    "kuzherka", "kuzholok", "kuzhyu", "kuzly", "kuzobyu", "kuzyol", "kuzyug", "kvina", "kviste",
    "kwando", "kwisa", "kyama", "kyanda", "kyay", "kych", "kychan", "kychas", "kydzshor",
    "kydzyis", "kydzyu", "kyeda", "kyjovka", "kylegyu", "kyll", "kylt", "kyltymyu", "kyma",
    "kymsas", "kynshor", "kynyol", "kyodza", "kyolda", "kyonga", "kypaky", "kyrchma", "kyrkyzya",
    "kyrtau", "kyrtomka", "kyryol", "kyryu", "kyssa", "kysyndy", "kyuno", "kyurzha", "kyuvayka",
    "kyzivka", "kyzym", "laborec", "labyonok", "lachte", "ladon", "ladonas", "lafnitz", "laguntik",
    "lahe", "lahkma", "lahn", "laibach", "laigne", "laisbach", "laita", "lakh", "lakhava",
    "lakhoma", "lakhost", "lakly", "lakovka", "lala", "lalbutxu", "lama", "lamba", "lambach",
    "lambro", "lamme", "lammer", "lamna", "lamochka", "lamsha", "landbach", "lane", "langete",
    "langry", "lankau", "lapa", "lapainia", "lapincs", "lapkovka", "laptapay", "laptevka", "lapur",
    "lareo", "largue", "larissos", "larit", "larraize", "larratxo", "larraz", "larrondo",
    "larruze", "larry", "lary", "lasarte", "laska", "lasosna", "lastreta", "lasva", "lata",
    "lataseno", "lato", "latorica", "latorita", "latrop", "latryk", "latxe", "laubach", "lauch",
    "lauchert", "lauer", "laufach", "lauquet", "laura", "laureta", "laut", "lauter", "lauwers",
    "lavant", "lavna", "lavra", "laweke", "laxbach", "laya", "layavozh", "laye", "layma", "laza",
    "lazh", "lazovka", "lbovka", "lebed", "lebot", "lebyodka", "leda", "lede", "ledenga", "ledma",
    "lednya", "ledzha", "leff", "legaire", "legar", "legoate", "legotho", "leguer", "lehbach",
    "lehrde", "leibi", "leie", "leimbach", "lein", "leina", "leine", "leira", "leirelva", "leisse",
    "leitha", "leitzach", "lekhta", "lekkem", "lekma", "lekmash", "lekos", "lema", "lemance",
    "lemanka", "lembach", "lemka", "lemme", "lemovzha", "lemp", "lempe", "lempua", "lemsha",
    "lemva", "lemya", "lemyu", "lemzha", "lenaelva", "lenevka", "lenka", "lenne", "lente", "lenva",
    "lepenac", "lepenc", "lepenec", "leppe", "lepsha", "leptayol", "lepyu", "lerbach", "lere",
    "lergue", "lertxuna", "lesse", "lesum", "letiza", "letma", "letnyaya", "leukbach", "leutra",
    "leva", "levash", "levaya", "levensau", "levinka", "levka", "levonka", "levzha", "lexaurdi",
    "lexeaga", "lezak", "lezape", "lezarde", "leze", "lezerana", "lezha", "lezkadi", "lezya",
    "liamone", "liaude", "liboumba", "lichte", "licupe", "liede", "lielupe", "lierbach", "liese",
    "lieser", "liesing", "lieux", "liffey", "liga", "lignon", "likhuta", "likova", "lillach",
    "lima", "limenda", "limmat", "limtayok", "limun", "linares", "linau", "lindach", "linde",
    "linder", "lingese", "linnepe", "linth", "lipacha", "lipbach", "lipka", "lipki", "lipleyka",
    "lipnya", "lipovets", "lippe", "lipsha", "lipyanka", "liri", "lirou", "lisinka", "liska",
    "lison", "lisos", "lister", "liswarta", "litava", "litavka", "littfe", "liver", "livo",
    "livojoki", "livoyoki", "livre", "lixiba", "lizerne", "lizhma", "lizna", "lizonne", "ljusnan",
    "llapi", "llastre", "lobach", "loban", "lobbach", "lobe", "lobische", "lobkha", "loch",
    "lochbach", "locheg", "locknitz", "lodde", "loddes", "loevka", "lohr", "lohrbach", "loia",
    "loidias", "loing", "loir", "loire", "loisach", "loja", "lokchim", "lokhoma", "lokhta",
    "lokia", "lokna", "loknya", "lokottsy", "loksha", "loksimer", "loktevka", "lokysta", "lolym",
    "lombach", "lomela", "lomik", "lomikha", "lominka", "lomnice", "lomovka", "lomya", "londoga",
    "lone", "longar", "longeves", "lonza", "lopatnic", "lopau", "lopeortu", "lopori", "lopsiya",
    "loptyuga", "lopva", "lopyu", "lormecke", "lorze", "loshytsa", "losinaya", "loska", "losmina",
    "lossa", "losse", "lotsane", "lottbek", "loucka", "loucna", "loue", "louros", "louyre",
    "lovat", "loyka", "loymina", "loyre", "lozon", "lozova", "lozoya", "lozva", "lubach",
    "lubenka", "lubet", "lubina", "lubochya", "lubsza", "lubyanka", "luch", "luchesa", "luder",
    "ludvozh", "ludyana", "ludza", "ludzinka", "luech", "lufira", "luga", "lugovka", "luhe",
    "lujerdiu", "luka", "lukavka", "lukenie", "lukh", "lukinka", "lukovaya", "lulonga", "lumda",
    "lumpun", "lundonga", "lundyuga", "lune", "lunga", "lunka", "lunmich", "lunponos", "lunvozh",
    "lunym", "lunyu", "luoba", "luol", "lupe", "luphephe", "luppbode", "lupta", "luptyug", "lupya",
    "lustovka", "luthern", "lutosha", "lutosnya", "lutter", "luya", "luyka", "luzege", "luzhana",
    "luzhanka", "luzhma", "luzhonka", "luznice", "luzoga", "lyaga", "lyamlya", "lyamtsa", "lyanos",
    "lychak", "lydias", "lymva", "lynga", "lyoch", "lyokkem", "lyokshor", "lyokyol", "lyom",
    "lyonva", "lyotma", "lysogor", "lysohir", "lystan", "lysva", "lytva", "lyubimka", "lyubka",
    "lyubovka", "lyubutka", "lyucher", "lyuga", "lyuk", "lyum", "lyumzha", "lyutenka", "lyuya",
    "lyuyka", "lyza", "lzha", "maalbeek", "maasti", "machekha", "machnac", "machok", "macta",
    "madalen", "madalena", "madmas", "madon", "madzha", "magash", "magdel", "maggia", "magieure",
    "magnan", "magra", "magree", "mahanadi", "mahury", "maibach", "maikchay", "main", "mainate",
    "maine", "maisach", "maizegi", "makan", "makinegi", "mako", "makovka", "maksanka", "maksara",
    "malapozu", "maletina", "malewa", "malitsa", "malkor", "malla", "malse", "malselva", "malta",
    "malxe", "malyava", "malyovka", "mamakan", "mamoksha", "mamux", "mana", "mandau", "mandel",
    "mando", "mangfall", "manguya", "manisene", "mank", "manoma", "manoy", "manse", "manuel",
    "manya", "mara", "marano", "marcq", "mardaka", "mareka", "marevka", "margusch", "margush",
    "marilhou", "maritsa", "mark", "marka", "markaida", "markayol", "markbach", "markha",
    "markovka", "marmande", "marne", "maronne", "marpe", "mars", "marsain", "martan", "martuni",
    "martxine", "martyur", "marupite", "maruri", "maryan", "maryinka", "mash", "mashok",
    "maslinka", "massa", "masse", "mastva", "mata", "matachel", "matkinyu", "matkoma", "matta",
    "matyogan", "matyug", "matz", "matzeta", "maulach", "maulne", "maumont", "maurepas", "maurine",
    "mausbach", "mavra", "maya", "mayata", "mayenne", "maygaza", "mayke", "maymakan", "mayna",
    "mayor", "mayskaya", "mayzas", "maza", "mazan", "mazanka", "mazarka", "maze", "mazhitsa",
    "mazik", "mazinka", "mazurka", "mdichka", "mecha", "mechet", "mechetka", "mechka", "mechkor",
    "medebach", "medem", "mediano", "medma", "medoza", "medvedka", "medyanka", "medynka",
    "megdovas", "meglinka", "mehdeaue", "mehe", "meholle", "meie", "melach", "melbbach", "melda",
    "melecha", "meletka", "melk", "mella", "mellier", "menda", "mendibil", "mendybay", "meneuz",
    "menkere", "menoge", "menthon", "menthue", "mentue", "menya", "menyega", "menza", "mera",
    "merderet", "meret", "mergbach", "merina", "meritsa", "merize", "merkova", "merwede",
    "merzbach", "meschena", "mesvrin", "mesyu", "metauro", "metevo", "metter", "mettma", "metuje",
    "metyolka", "meuse", "meuzin", "meza", "mezen", "mezenka", "mezere", "mezhitsa", "mezhovka",
    "mgla", "mianka", "miass", "micha", "michayol", "michayu", "michik", "michkas", "midou",
    "midouze", "mien", "mietzel", "mikawa", "mikayol", "mikhydra", "mikiena", "mikyakh",
    "miletina", "miljacka", "milz", "mimente", "mina", "mindel", "minger", "minolga", "minor",
    "mintegi", "mintsas", "minyar", "miodet", "misa", "miselya", "miss", "mistel", "mitbach",
    "mitin", "mitka", "mitkirey", "mituva", "miura", "miuss", "miyaki", "mjolnaan", "mlynica",
    "mnoga", "mnoha", "moalven", "mocha", "mochan", "mochegay", "mociur", "modan", "modau",
    "moesa", "mogak", "mogne", "mogot", "mogza", "mohelka", "mohlin", "mohne", "moivre", "mokla",
    "moksha", "molchna", "molignee", "moll", "molochay", "molochis", "mologzha", "moloksha",
    "molyobka", "monaga", "monbach", "moncha", "mongon", "montana", "montoku", "montone", "monza",
    "moohool", "moolhool", "moorbach", "moosach", "moosalb", "moraca", "morales", "morava",
    "moravice", "moravka", "morbras", "mordova", "morge", "morges", "morkai", "morkusha", "morkva",
    "morlans", "mornbach", "morterua", "morye", "moseke", "moselle", "moshlya", "moshna",
    "moshnaya", "moshnya", "mosson", "mostnica", "mostovka", "mostva", "motawa", "motel", "motima",
    "motko", "motroi", "motzaren", "mouline", "mouzon", "moyero", "mozha", "mshaga", "mubach",
    "mudayok", "mudora", "mugay", "mugitza", "mugnone", "muhlbach", "muhlenau", "muhre", "mukhen",
    "mulde", "mulmisch", "multanka", "muluk", "mulyk", "mumlava", "mumling", "muna", "munabe",
    "munay", "mundo", "munegi", "muniota", "munjava", "munka", "munkelva", "munttar", "muntto",
    "muran", "muravka", "murbach", "murdyug", "murg", "murin", "murka", "murkozka", "murr",
    "murtmash", "muryu", "murz", "murza", "muse", "mushawe", "mushuga", "musirma", "muska",
    "musorka", "mustar", "mustjogi", "mutanen", "mutio", "mutnitsa", "mutunya", "mutzbach",
    "muvizha", "muxika", "muya", "myagdoma", "mykhydra", "myla", "mylvozh", "mynajoki", "myrtova",
    "myrtyyu", "mysanka", "mysla", "mysovaya", "mytets", "naab", "naafbach", "nacedero", "nacha",
    "nachka", "nadas", "nadasa", "nadym", "nagold", "nahe", "nahle", "nais", "nalez", "nalimyu",
    "nalon", "nalya", "namgang", "nanhe", "nansa", "nanyakh", "napte", "nara", "naratly",
    "narbaiz", "narchug", "narew", "naritka", "naritne", "narma", "narmada", "naroda", "nartiya",
    "naruta", "narva", "nashiga", "nassach", "nausta", "nauze", "nauzon", "navia", "navlya",
    "nazi", "nebdinga", "nebel", "nebich", "neblon", "necha", "neckar", "necker", "nedra",
    "nedzyuga", "neerdar", "neetze", "neez", "nega", "neger", "neira", "nekrasa", "neledina",
    "nelmenga", "nelnega", "nelnyuga", "neloksa", "nelsha", "nelym", "neman", "nemda", "nemdezh",
    "nemich", "nemka", "nemonin", "nemyd", "nemyn", "nemyt", "nenekha", "nenga", "nenskra",
    "nenya", "nepil", "nercha", "nerekhta", "nereta", "neretva", "nerga", "nerina", "neris",
    "nerl", "nerskaya", "nersma", "nerussa", "nervia", "nervion", "nesque", "nessa", "nesse",
    "neste", "nestos", "nethe", "netoma", "netphe", "nette", "netze", "neumagen", "neva",
    "nevesel", "nevezis", "nevra", "neya", "nezarka", "neznayka", "ngatiawa", "niael", "niayol",
    "nida", "nidda", "nidder", "nidelva", "nidz", "nied", "niedrupe", "niedzyu", "nieme",
    "nierbach", "niers", "niese", "nieste", "nievole", "niger", "nikifora", "nila", "nile",
    "nilech", "nilydz", "nimenga", "nims", "ninkoma", "nisava", "nisha", "nishma", "nister",
    "nitelva", "nitra", "niva", "nivnicka", "nivyu", "niyap", "niyayu", "nize", "nizyana", "noba",
    "nobach", "nodbach", "nodoga", "nohain", "noireau", "noirieu", "nola", "nolgash", "nolka",
    "nolya", "nomzha", "nonette", "noord", "nora", "nordbach", "norin", "norka", "norran",
    "norura", "nosa", "nosh", "nosim", "notec", "nouere", "novaya", "novguda", "novik", "nozik",
    "nozma", "nrnadzor", "ntshe", "nudysh", "nugaal", "nugush", "nuhne", "nuksha", "nulka",
    "numgi", "nurda", "nurma", "nuthe", "nuya", "nuzh", "nuzha", "nuzhenka", "nuzhinka", "nuzhna",
    "nuzyk", "nyagak", "nyagu", "nyanda", "nyarshor", "nydyb", "nylga", "nylozhka", "nyobyu",
    "nyovra", "nyrmych", "nyromka", "nyrya", "nyrza", "nysh", "nysha", "nyuba", "nyukchim",
    "nyukhcha", "nyukzha", "nyul", "nyulach", "nyulchim", "nyuma", "nyumled", "nyumyd", "nyurikh",
    "nyurym", "nyushor", "nyuvyu", "nyuzhma", "oahahah", "oawa", "obdyr", "obelna", "oberbek",
    "obesta", "obitele", "obmen", "oborlya", "obva", "ocher", "ocheya", "ochtum", "ochyor", "ocna",
    "odeborn", "odenbach", "oder", "odrava", "odron", "odyu", "odyyu", "oelbach", "oelze",
    "oester", "oglat", "ohebach", "oial", "oiaola", "oinati", "oiorta", "ojewek", "okano", "okhta",
    "okhtoma", "okillegi", "okin", "okkervil", "okna", "okobi", "okola", "okos", "okpara", "olabe",
    "olabizar", "olain", "olakortu", "olaondo", "olariaga", "olava", "olekte", "olenitsa",
    "olerrea", "oleska", "oleta", "olkha", "olkhovka", "olkhush", "ollaun", "olloko", "olma",
    "olmeta", "olomna", "olona", "olonka", "olova", "olshanka", "olym", "omelnik", "omen",
    "omniczka", "omulew", "omulupe", "omut", "omutnaya", "omza", "ondallu", "ondalutz", "ondarra",
    "ondartza", "ondava", "onolva", "onut", "onyl", "opavice", "opawica", "oplelva", "opton",
    "optukha", "orbiquet", "orchyk", "ordo", "oreb", "oredezh", "orel", "oreuse", "orge", "orilka",
    "orlinka", "orlitsa", "orlovka", "ormakio", "ormaola", "oropa", "orradre", "orta", "ortina",
    "ortzaika", "ortze", "oruchan", "orvanne", "orya", "oryol", "osanovka", "osen", "oshap",
    "oshmas", "osinaga", "osinalde", "osineta", "osinka", "osinovka", "oska", "oskina", "osolo",
    "ososina", "ospa", "osse", "osterau", "osto", "ostruzna", "osuga", "otano", "otorma",
    "otraitz", "otsate", "otsategi", "otuzka", "otzaurte", "ouanary", "ouanne", "ouatier",
    "ouette", "oule", "ouse", "ouveze", "ovinnaya", "oxhe", "oxineta", "oyash", "ozerka", "ozerna",
    "ozernaya", "ozvanka", "ozyorka", "pachikha", "pachoga", "paco", "padul", "pago", "pagotxa",
    "pakhma", "pakhotka", "pala", "palapa", "palatu", "paleshka", "palnaya", "palpate", "palsa",
    "palym", "palyu", "pana", "panaro", "pangur", "pantylka", "panzelka", "parch", "parchyu",
    "paren", "paroma", "parrett", "partsa", "paseka", "pasha", "pasheva", "pashnyak", "pasynok",
    "patra", "patsa", "paulejas", "pava", "pavlovka", "pcinja", "pechenga", "pechuga", "pededze",
    "pedetsi", "pedranzo", "peguza", "peksum", "pela", "pelenga", "pelshma", "pena", "penadi",
    "penalba", "penijogi", "peninga", "penza", "penze", "peremera", "perenal", "perevid",
    "perovka", "persha", "perya", "peskar", "pester", "petenka", "petritsa", "petrovka", "pevk",
    "peza", "pfatter", "pfreimd", "piasnica", "piasnitz", "pidma", "pieninka", "pikoaga", "pilda",
    "pilga", "pilona", "pinezhka", "pingel", "pingisha", "pintano", "pioli", "pioverna", "pishlya",
    "pistynka", "piteyka", "piva", "pixuaga", "piya", "piyu", "pizhanka", "pizhanya", "pizma",
    "pizya", "platone", "platonis", "plava", "plebach", "plesna", "plima", "plisunka", "plomondo",
    "ploskaya", "plotnica", "plovutka", "plusona", "poch", "pochaina", "pochayna", "pocilon",
    "poda", "podgorna", "podlomka", "poezh", "poim", "poinga", "poksha", "polazna", "polevaya",
    "polipaso", "politsa", "polna", "polom", "polonka", "polovka", "poltoma", "polva", "polynka",
    "pomut", "poncha", "ponikla", "ponil", "ponka", "popigay", "popolta", "popyuga", "pora",
    "porijogi", "poros", "porra", "porus", "porusya", "poserda", "postolka", "potka", "potudan",
    "potyu", "pouya", "poyma", "pozh", "pozha", "pozheg", "pozhva", "pozhyog", "presna", "prims",
    "protoka", "prudovka", "psefir", "psekups", "psheha", "pshekha", "puchkoma", "pudega", "pudem",
    "puiu", "pukawka", "pukster", "pulla", "puloma", "pult", "pulwa", "punga", "punkva", "pura",
    "puras", "purcaru", "purezhka", "purna", "purnach", "purnaya", "purnema", "pursovka",
    "pustaya", "puttlach", "putyla", "putylka", "puyga", "puzym", "pyataya", "pyhajoki", "pykara",
    "pykhovka", "pykhta", "pyot", "pyrsyu", "pyshchug", "pyshega", "pyshkets", "pytyryu", "pyzep",
    "qarechay", "qorghas", "quintana", "quorra", "qurucay", "rabiosa", "rabiusa", "rada",
    "radbusa", "radbuza", "radika", "radike", "radisa", "radol", "radoljna", "radomka", "raduga",
    "radunia", "raevka", "rakahuri", "rakdong", "rakhma", "rakitnya", "rakovka", "ramenka",
    "rance", "rankbach", "ranna", "ranova", "rapida", "rapido", "rapina", "raplya", "rappbode",
    "rasthene", "rasyu", "ratsa", "rausor", "ravan", "rayevka", "rayna", "razvily", "rechitsa",
    "recknitz", "redlbach", "redon", "regal", "regino", "rehbach", "reigne", "reisa", "remda",
    "remel", "remolino", "renne", "repe", "repnaya", "reppisch", "resava", "reshetka", "ressa",
    "ressegue", "retourne", "revna", "rezh", "rhene", "rhine", "rhome", "rhony", "rhume",
    "ribitsya", "rida", "rietbaan", "rimavica", "rinda", "rioseco", "rioya", "rioyo", "ripa",
    "rishi", "risquero", "rivalier", "river", "riveris", "rivok", "rize", "roatxi", "robec",
    "rocavao", "roda", "rodach", "roga", "rogalik", "rogneaux", "rogozina", "rohrach", "rohu",
    "roja", "rokach", "rokytna", "rolante", "romaine", "romanee", "rombach", "ropelva", "ropotamo",
    "rosandra", "roselle", "rossel", "rosselle", "rossosh", "rosta", "rotbach", "roth", "rottach",
    "rottum", "roumer", "rouvre", "rovaam", "rovets", "rovok", "rozan", "rozhanka", "rozhka",
    "roztoka", "rubikha", "ruda", "rudamina", "rudnia", "ruja", "rujoux", "rukavets", "ruksha",
    "rulles", "runa", "ruoshui", "rusakova", "rusava", "russa", "russkaya", "rutia", "rutka",
    "rvanets", "ryabinka", "ryauzyak", "rybitsa", "rybka", "rybnaya", "rybnitsa", "ryksha",
    "rykusha", "rynda", "ryumina", "rzhevka", "sablya", "sada", "sadak", "sadar", "sadon", "safen",
    "saghyz", "sagoeta", "salair", "salajogi", "salanfe", "saline", "saliste", "sallueta", "salon",
    "sals", "saltuona", "salturri", "salubita", "salwey", "salya", "samets", "samovets", "sanarka",
    "sandoain", "sangueze", "sanna", "sanon", "santoire", "saone", "sapolga", "sapuela", "saraso",
    "sarce", "sardyk", "sarga", "sarjanka", "sarmento", "sarnajur", "sars", "sartaka", "sartamak",
    "sarva", "sarvazel", "sarvozh", "saryu", "sasillo", "saska", "sasna", "sastegi", "sasturri",
    "satadree", "satava", "satkula", "satoka", "satrija", "saubach", "sauer", "saulx", "saumort",
    "sauna", "savina", "sayn", "sayta", "saza", "scance", "scardon", "schaale", "schijn",
    "schmiech", "schonach", "schrote", "scorff", "scrivia", "sebin", "sebou", "secchia", "secone",
    "seconec", "sedelle", "sedyol", "sedzsiya", "seebach", "seerhein", "segur", "segzha", "seiche",
    "seille", "selena", "selle", "selma", "selmenga", "selune", "selves", "sema", "semene",
    "semenek", "semine", "semouse", "senarats", "sennaya", "senpere", "sensee", "sentelek",
    "sepozhka", "sepych", "serava", "serchio", "serdtse", "serena", "seret", "sereul", "serp",
    "serrano", "sertynya", "serva", "seryona", "sesek", "sesto", "sestra", "sesuvis", "setta",
    "seuge", "seulles", "seulline", "seva", "severnik", "sevo", "seyon", "seza", "sezukh",
    "shacha", "shada", "shaderka", "shakhe", "shaksha", "shalma", "shaman", "shaparka", "shape",
    "shapkina", "shapsha", "sharanga", "sharlama", "shat", "shava", "shedra", "shegmas", "shelek",
    "shelon", "shenga", "sherda", "sheshma", "shetyas", "shevinka", "shida", "shids", "shilik",
    "shire", "shiringa", "shirova", "shishov", "shiverta", "shivoron", "shivrey", "shlina",
    "shlinka", "shmil", "shoba", "shocha", "shoksha", "sholda", "shombash", "shora", "shozhym",
    "shuda", "shudelka", "shuksha", "shulka", "shunduk", "shuvan", "shuzhega", "shuzhlep", "siate",
    "sibirka", "sichter", "sigavey", "sima", "simeto", "simile", "simka", "sinaise", "sinara",
    "sinn", "sinyukha", "sioule", "sioulet", "sirvinta", "sisian", "sitnitsa", "sitter",
    "sivashur", "sivushka", "siya", "sizma", "sjoa", "skat", "skawica", "skniga", "skrypca",
    "slampe", "slapanka", "slonivka", "smakupe", "smeltale", "smolinka", "smosh", "smozh",
    "snezhet", "snov", "snova", "soana", "sodima", "soga", "sogozha", "sokero", "solda",
    "soldatka", "soloire", "solona", "solonaya", "solosora", "soltau", "soltonka", "solyanka",
    "somme", "sona", "sondema", "sonegi", "songa", "sonsbeek", "sontra", "sora", "sorabil",
    "sorgin", "sorginek", "sorma", "sornin", "sorom", "sorpe", "sosenka", "sosnca", "sosnova",
    "sosnovka", "sotka", "soudaine", "souffel", "sovza", "soyma", "spasivka", "spasovka",
    "spasska", "spengla", "spring", "srpina", "sruoja", "stara", "starzel", "steinach", "steir",
    "sterlya", "steyr", "stobnica", "strelina", "strelnya", "striene", "strigova", "strona",
    "strule", "stryzhen", "subas", "subash", "suceava", "sudak", "sudogda", "sudoma", "sudzha",
    "suerrin", "sueta", "sugash", "sugoy", "suhl", "suippe", "sukha", "sukhoda", "sukhovka",
    "sula", "sultsys", "sulzbach", "suma", "sumara", "sumutru", "suna", "sunda", "sundoba",
    "sundrun", "suolama", "suosa", "supra", "sura", "sure", "surgut", "surkhrud", "surkul",
    "susanka", "sustatxo", "sutlej", "suunduk", "suvarysh", "suyda", "svapa", "svarcava",
    "svartan", "svartsan", "svetitsa", "svetlaya", "svetluga", "svicha", "svirzh", "svitene",
    "svitinys", "swale", "swieza", "syava", "syezha", "sylva", "synya", "syomya", "syova",
    "syraya", "syrtan", "syrvozh", "syuksyum", "syurva", "syuyga", "syuzum", "syuzva", "syuzyu",
    "syuzyum", "syvtuga", "tabani", "tabat", "tabyakha", "tacon", "tagozhma", "tagul", "tajavias",
    "taka", "talabor", "talaia", "talaron", "talatshi", "talitsa", "talma", "talovka", "talsha",
    "taltsiya", "talym", "tamlyk", "tamout", "tana", "tangnary", "tanlova", "tanoga", "tapeni",
    "tapoa", "tapti", "tara", "taraba", "tarako", "taraksa", "tarlung", "tarnon", "tarnova",
    "tarsap", "tart", "tartaka", "tartas", "tasa", "taseyeva", "tashelka", "tashenka", "tashevka",
    "tashla", "tashtyp", "tastus", "tatarka", "tatosh", "tatta", "tatula", "taurion", "tausalas",
    "taute", "tavalga", "tavo", "tavolga", "tavrenga", "tayruk", "tazha", "teche", "tegus",
    "teichl", "tekos", "telgaza", "telleri", "telpos", "telpoz", "temnaya", "temnik", "temnitz",
    "teneke", "tenenys", "tenke", "tepla", "teplica", "teplovka", "terebla", "tereblja",
    "tereblya", "terebna", "ternavka", "ternovka", "terrette", "tersul", "teryukha", "teshnyar",
    "teterka", "tetyorka", "teya", "teysonne", "therain", "thin", "tholon", "thongue", "thouet",
    "tiasca", "timenka", "timpton", "tiobut", "tiraldai", "tirino", "tiskos", "tissa", "tjonger",
    "tmaka", "tocedo", "togayka", "togul", "tojalas", "tolenus", "tolerme", "toleto", "tollo",
    "tolman", "tolshma", "tolstaya", "tolva", "tolya", "tolzes", "tomasha", "tomba", "tompo",
    "tonas", "tonga", "tora", "torfaen", "torghay", "torgosha", "torgun", "tortymka", "torysa",
    "toss", "tota", "tova", "toylok", "tozhiga", "trait", "traska", "tray", "treba", "trec",
    "trey", "trient", "trigno", "trincou", "trkmanka", "tronto", "troska", "trot", "trouille",
    "trualbe", "trubach", "trubezh", "trudy", "tsapeni", "tsareva", "tsaritsa", "tsebyuga",
    "tserukha", "tseyadon", "tsimla", "tsitse", "tuga", "tula", "tulazhka", "tulcis", "tuleblya",
    "tulitsa", "tulka", "tuluyul", "tuluzka", "tumana", "tumany", "tumna", "tundinka", "tunguda",
    "tunka", "turanka", "turano", "turdey", "turgen", "turianka", "turukhan", "turungas",
    "turupya", "turyanka", "turychka", "tuya", "tuyga", "tuyla", "tuytomyu", "tuzovka", "txalingo",
    "txarakoa", "txarale", "txerrail", "tximitx", "txiplao", "txoko", "tyamka", "tyater",
    "tyavsora", "tyazhin", "tyloyka", "tyoplaya", "tyukyan", "tyulyan", "tyuma", "tyumber",
    "tyuryush", "tyzyl", "tzapeni", "tzapok", "uastran", "ubago", "ubao", "ubelbach", "ubera",
    "ubide", "ubidieta", "ubilluts", "ubukun", "udava", "uddjokk", "udev", "udisna", "udova",
    "udryuma", "udyes", "udyov", "udyurma", "uftyuga", "ugaskoa", "ugdym", "ugdymyu", "uharka",
    "ukerreka", "ukhta", "ukhtanga", "ukhtitsa", "ukhtomka", "ukhvazh", "ukrop", "uksunay",
    "uksyum", "ukyu", "ulba", "ulen", "ulesha", "ulfa", "ulicka", "ulmbach", "ulom", "uloma",
    "ulomka", "uluyelga", "ulvich", "umanka", "umaran", "umendi", "umirka", "umpfer", "undabe",
    "undula", "undysh", "unezhma", "unga", "ungor", "ungra", "unola", "untemka", "untsain",
    "untxin", "untzilla", "unzhitsa", "upinka", "uranka", "urap", "urasketa", "uratza", "urbi",
    "urdaburu", "urdaiene", "urdamana", "urdanesi", "urdazuri", "urdoma", "urdungio", "urederra",
    "uren", "urez", "urga", "urgierri", "urguza", "urkan", "urko", "urkutza", "urlio", "urma",
    "urmi", "urralegi", "urruzuno", "ursalto", "ursdon", "ursul", "urtzuloa", "urtzuri", "uruna",
    "urushten", "urynga", "uryzhar", "usek", "usha", "ushayka", "ushinka", "ushma", "usiain",
    "uskalyk", "usolka", "uspenka", "ustia", "ustjanka", "ustyuba", "usva", "utemka", "uteni",
    "utka", "utkash", "utkul", "utosjoki", "utsjoki", "utyelga", "utzurri", "uvarovka", "uvdu",
    "uvelka", "uxondo", "uzaksa", "uzlikha", "uzma", "uzola", "uztarroz", "uzyan", "vaana",
    "vablya", "vacheres", "vadma", "vadok", "vadya", "vadyuga", "vagil", "vagran", "vaijoki",
    "vaijuuha", "vakhtan", "valay", "vald", "valfondo", "valgomka", "valka", "valles", "valme",
    "valouse", "valpes", "vama", "vanajogi", "vanan", "vandysh", "vannetin", "vapol", "vara",
    "varagno", "vareze", "varezhka", "varguno", "varinka", "varvazh", "varyash", "varyazh",
    "varzha", "varzi", "varzina", "varzinka", "vashana", "vasina", "vaskina", "vatoma", "vaya",
    "vaymizh", "vedrich", "veletma", "velikaya", "velva", "velya", "velyu", "velyugan", "venant",
    "vengel", "venoksha", "veore", "verda", "verdoble", "vere", "verebya", "verkusha", "vernason",
    "veronda", "verse", "vertuba", "veryazha", "veryu", "veryuga", "vesdre", "veseta", "veshka",
    "veshkoma", "veslyana", "vesubie", "vesym", "vetma", "veude", "veynka", "vezere", "vezhma",
    "viaz", "vidima", "vidsupe", "viedryc", "vierre", "viesata", "vija", "vika", "vikhra",
    "viliga", "vilva", "vinka", "viosne", "vire", "virma", "viroin", "visakis", "visha", "vishera",
    "vishnya", "visim", "vitsa", "vitushka", "vizhay", "vizhayka", "vizma", "vlasina", "vlist",
    "vnina", "vocha", "voepolka", "voie", "vokhila", "vokhma", "vokhonka", "vokhta", "volcas",
    "volches", "volchja", "volchya", "volga", "volgusha", "volinka", "volka", "volkhov", "volkhya",
    "volkota", "volkova", "volost", "volozhka", "volp", "volya", "volyuga", "voncha", "voncho",
    "vonco", "vondanka", "vondozh", "vononga", "vonzhuga", "vopets", "vorgol", "vorobina", "voron",
    "vorona", "voronets", "voronka", "vorozhba", "vorya", "vostra", "votrya", "votto", "vovcha",
    "voya", "voykar", "voylas", "voyninga", "voynitsa", "voyvozh", "vozhega", "vozhma", "vozhoyka",
    "vrin", "vshivka", "vuktyl", "vusa", "vuzhi", "vyachka", "vyanitsa", "vyas", "vyatkina",
    "vyazma", "vyazovka", "vycha", "vydrin", "vydritsa", "vyna", "vyoksa", "vyorda", "vyrezka",
    "vyryp", "vytebet", "vytegra", "vyug", "vyvenka", "waal", "waaltje", "wahnbach", "wambach",
    "wampe", "wandse", "wanne", "wapel", "wapusza", "warenne", "warme", "warnau", "wate", "watter",
    "wehrbach", "weiach", "weil", "weizbach", "wellbach", "wenne", "werse", "wethau", "wetlina",
    "wiar", "wiebach", "wiedrycz", "wiesent", "wilcza", "wiltz", "wimereux", "winkel", "wisenta",
    "wnion", "wondreb", "worona", "wublitz", "wuhle", "wurm", "wurmbach", "xabros", "xabroze",
    "xanthe", "xarmona", "xiusmear", "xubiketa", "xznidon", "xznydon", "yaba", "yagoshur",
    "yakhroma", "yakhrust", "yalma", "yamansu", "yancher", "yanga", "yangelka", "yanyya",
    "yarovka", "yarto", "yarysh", "yaschera", "yasenka", "yashka", "yashkul", "yasnovka",
    "yatriya", "yaubaza", "yauza", "yauzyak", "yavas", "yavon", "yazinka", "yazvynka", "yedenga",
    "yeghegis", "yegona", "yegrinka", "yekshal", "yelbak", "yelet", "yelevka", "yelga", "yelisera",
    "yelmane", "yelomza", "yelovka", "yelyuga", "yemekh", "yemets", "yemsna", "yemurtla",
    "yendrika", "yendyuga", "yengish", "yentala", "yenyu", "yeranka", "yerba", "yerdva", "yergol",
    "yermish", "yertym", "yerych", "yeryk", "yerzha", "yetypur", "yevbaza", "yevda", "yevre",
    "yezhreka", "yezhuga", "ylijoki", "yolda", "yolva", "yontala", "yortom", "yortym", "youshui",
    "yovva", "yozhuga", "yron", "yuchka", "yuga", "yukolka", "yulovka", "yuma", "yumata",
    "yumzenga", "yunda", "yunga", "yungur", "yurga", "yuribey", "yurika", "yurka", "yurmash",
    "yuroma", "yuromka", "yurtik", "yurumka", "yushut", "yutsa", "yutymas", "yuzhinka", "yvron",
    "zabalain", "zabaleta", "zabordi", "zadnyaya", "zagyva", "zaimka", "zalazna", "zaldana",
    "zaldi", "zalomka", "zalomska", "zamglay", "zamhlai", "zamhlay", "zang", "zaprudka", "zardaia",
    "zarnica", "zarraga", "zarrubi", "zaturio", "zavitaya", "zdobnice", "zebain", "zehlov",
    "zeimena", "zejbro", "zelena", "zelenaya", "zelenka", "zelivka", "zelyonka", "zerekla",
    "zestegi", "zeyva", "zhaba", "zhalka", "zhanabay", "zharykha", "zhelcha", "zhelkuar",
    "zhelonya", "zhemtala", "zherd", "zhilinka", "zhinya", "zhukopa", "zhuzhla", "ziako", "zien",
    "zigan", "zigaza", "zijl", "zilair", "ziminka", "zimukha", "ziorza", "zitava", "zmeevka",
    "zmeyevka", "zmeyovka", "znobowka", "zohajur", "zokotegi", "zorzor", "zuatzu", "zuazola",
    "zubiaga", "zubieta", "zubitxo", "zubitxu", "zugarate", "zuja", "zumaleku", "zumeldi", "zuya",
    "zvanka", "zverinka", "zvirgzde", "zwalm", "zwettl", "zwolenka", "zyryanka", "zyuzelka",
];

#[cfg(test)]
mod tests {
    use super::DEFAULT_RIVER_NAMES;

    #[test]
    fn default_river_names_are_sorted_and_cover_late_alphabet() {
        assert!(DEFAULT_RIVER_NAMES
            .windows(2)
            .all(|window| window[0] < window[1]));
        assert!(DEFAULT_RIVER_NAMES.iter().any(|name| name.starts_with('p')));
        assert!(DEFAULT_RIVER_NAMES.iter().any(|name| name.starts_with('z')));
    }
}
